# Generated by Django 5.2.1 on 2025-10-21 13:11

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('team_place', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('registered_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('is_coach', models.BooleanField(default=False)),
                ('is_referee', models.BooleanField(default=False)),
                ('profile_image', models.ImageField(blank=True, default='profile_images/default.png', null=True, upload_to='profile_images/')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('place', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FederationRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FrontendTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', help_text="Theme name (e.g., 'default', 'dark', 'light')", max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=False, help_text='Set as the active theme for the frontend')),
                ('primary_color', models.CharField(default='#0d47a1', help_text='Primary brand color (hex)', max_length=7)),
                ('primary_light', models.CharField(default='#5e7ce2', help_text='Light variant of primary color', max_length=7)),
                ('primary_dark', models.CharField(default='#002171', help_text='Dark variant of primary color', max_length=7)),
                ('secondary_color', models.CharField(default='#f50057', help_text='Secondary accent color', max_length=7)),
                ('background_default', models.CharField(default='#f5f5f5', help_text='Default background color', max_length=7)),
                ('background_paper', models.CharField(default='#ffffff', help_text='Paper/card background color', max_length=7)),
                ('text_primary', models.CharField(default='#212121', help_text='Primary text color', max_length=7)),
                ('text_secondary', models.CharField(default='#757575', help_text='Secondary text color', max_length=7)),
                ('font_family', models.CharField(default='BeVietnam, Roboto, Helvetica, Arial, sans-serif', help_text='Font family stack', max_length=200)),
                ('font_size_base', models.IntegerField(default=14, help_text='Base font size in pixels')),
                ('font_weight_normal', models.IntegerField(default=400, help_text='Normal font weight')),
                ('font_weight_medium', models.IntegerField(default=500, help_text='Medium font weight')),
                ('font_weight_bold', models.IntegerField(default=700, help_text='Bold font weight')),
                ('border_radius', models.IntegerField(default=8, help_text='Default border radius in pixels')),
                ('spacing_unit', models.IntegerField(default=8, help_text='Base spacing unit in pixels')),
                ('button_border_radius', models.IntegerField(default=8, help_text='Button border radius')),
                ('card_elevation', models.IntegerField(default=2, help_text='Card shadow elevation')),
                ('table_row_hover', models.CharField(default='#f5f5f5', help_text='Table row hover color', max_length=7)),
                ('custom_tokens', models.JSONField(blank=True, default=dict, help_text='Advanced custom theme tokens (JSON format)')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Frontend Theme',
                'verbose_name_plural': 'Frontend Themes',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rank_order', models.IntegerField(default=0)),
                ('grade_type', models.CharField(choices=[('inferior', 'Inferior Grade'), ('superior', 'Superior Grade')], default='inferior', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=10)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AnnualVisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('visa_status', models.CharField(choices=[('available', 'Available'), ('expired', 'Expired'), ('not_available', 'Not Available')], default='not_available', max_length=15)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_visas', to='api.athlete')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('solo', 'Solo'), ('teams', 'Teams'), ('fight', 'Fight')], default='solo', max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('mixt', 'Mixt')], default='mixt', max_length=20)),
                ('first_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_place_categories', to='api.athlete')),
                ('second_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_place_categories', to='api.athlete')),
                ('third_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_place_categories', to='api.athlete')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryAthlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.athlete')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_athletes', to='api.category')),
            ],
            options={
                'unique_together': {('category', 'athlete')},
            },
        ),
        migrations.AddField(
            model_name='category',
            name='athletes',
            field=models.ManyToManyField(blank=True, related_name='categories', through='api.CategoryAthlete', to='api.athlete'),
        ),
        migrations.CreateModel(
            name='CategoryTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_teams', to='api.category')),
            ],
        ),
        migrations.AddField(
            model_name='athlete',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='athletes', to='api.city'),
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='club_logos/')),
                ('address', models.TextField(blank=True, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to='api.city')),
                ('coaches', models.ManyToManyField(blank=True, related_name='coached_clubs', to='api.athlete')),
            ],
        ),
        migrations.AddField(
            model_name='athlete',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='athletes', to='api.club'),
        ),
        migrations.AddField(
            model_name='category',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='api.competition'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='federation_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='athletes', to='api.federationrole'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='current_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_athletes', to='api.grade'),
        ),
        migrations.CreateModel(
            name='GradeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obtained_date', models.DateField(auto_now_add=True)),
                ('level', models.CharField(choices=[('good', 'Good'), ('bad', 'Bad')], default='good', max_length=10)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('exam_place', models.CharField(blank=True, max_length=100, null=True)),
                ('technical_director', models.CharField(blank=True, max_length=100, null=True)),
                ('president', models.CharField(blank=True, max_length=100, null=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_history', to='api.athlete')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.grade')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='api.competition')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='api.group'),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(choices=[('qualifications', 'Qualifications'), ('semi-finals', 'Semi-Finals'), ('finals', 'Finals')], default='qualifications', max_length=20)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('blue_corner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blue_corner_matches', to='api.athlete')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='api.category')),
                ('red_corner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='red_corner_matches', to='api.athlete')),
                ('referees', models.ManyToManyField(limit_choices_to={'is_referee': True}, related_name='refereed_matches', to='api.athlete')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='api.athlete')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalVisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('health_status', models.CharField(choices=[('approved', 'Approved'), ('denied', 'Denied')], default='denied', max_length=10)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_visas', to='api.athlete')),
            ],
        ),
        migrations.CreateModel(
            name='RefereeScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red_corner_score', models.IntegerField(default=0)),
                ('blue_corner_score', models.IntegerField(default=0)),
                ('winner', models.CharField(blank=True, choices=[('red', 'Red Corner'), ('blue', 'Blue Corner')], max_length=10, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referee_scores', to='api.match')),
                ('referee', models.ForeignKey(limit_choices_to={'is_referee': True}, on_delete=django.db.models.deletion.CASCADE, to='api.athlete')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('categories', models.ManyToManyField(blank=True, limit_choices_to={'type': 'teams'}, related_name='team_categories', through='api.CategoryTeam', to='api.category')),
            ],
        ),
        migrations.AddField(
            model_name='categoryteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_categories', to='api.team'),
        ),
        migrations.AddField(
            model_name='category',
            name='first_place_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_place_team_categories', to='api.team'),
        ),
        migrations.AddField(
            model_name='category',
            name='second_place_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_place_team_categories', to='api.team'),
        ),
        migrations.AddField(
            model_name='category',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='category_teams', through='api.CategoryTeam', to='api.team'),
        ),
        migrations.AddField(
            model_name='category',
            name='third_place_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_place_team_categories', to='api.team'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='athletes', to='api.title'),
        ),
        migrations.CreateModel(
            name='TrainingSeminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('place', models.CharField(max_length=100)),
                ('athletes', models.ManyToManyField(blank=True, related_name='training_seminars', to='api.athlete')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryAthleteScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_scores', to='api.athlete')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_scores', to='api.category')),
                ('referee', models.ForeignKey(limit_choices_to={'is_referee': True}, on_delete=django.db.models.deletion.CASCADE, to='api.athlete')),
            ],
            options={
                'unique_together': {('category', 'athlete', 'referee')},
            },
        ),
        migrations.CreateModel(
            name='CategoryTeamScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_scores', to='api.category')),
                ('referee', models.ForeignKey(limit_choices_to={'is_referee': True}, on_delete=django.db.models.deletion.CASCADE, to='api.athlete')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_scores', to='api.team')),
            ],
            options={
                'unique_together': {('category', 'team', 'referee')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='categoryteam',
            unique_together={('category', 'team')},
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='api.athlete')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.team')),
            ],
            options={
                'unique_together': {('team', 'athlete')},
            },
        ),
    ]
