# Generated by Django 5.2.1 on 2026-02-08 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        ('auth', '0013_userproxy'),
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('landing.event',),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_athletes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='athlete',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='athlete',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='athlete',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='athlete',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_athletes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='athlete',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='athlete', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='athletematch',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_matches', to='api.athlete'),
        ),
        migrations.AddField(
            model_name='athletematch',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='athlete_matches', to='landing.event'),
        ),
        migrations.AddField(
            model_name='athletematch',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_athlete_matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='landing.event'),
        ),
        migrations.AddField(
            model_name='categoryathlete',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.athlete'),
        ),
        migrations.AddField(
            model_name='categoryathlete',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_athletes', to='api.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='athletes',
            field=models.ManyToManyField(blank=True, related_name='categories', through='api.CategoryAthlete', to='api.athlete'),
        ),
        migrations.AddField(
            model_name='categoryathletescore',
            name='athlete',
            field=models.ForeignKey(blank=True, help_text='Athlete being scored (null for team scores)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_scores', to='api.athlete'),
        ),
        migrations.AddField(
            model_name='categoryathletescore',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_scores', to='api.category'),
        ),
        migrations.AddField(
            model_name='categoryathletescore',
            name='referee',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_referee': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.athlete'),
        ),
        migrations.AddField(
            model_name='categoryathletescore',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_scores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categoryathletescore',
            name='team_members',
            field=models.ManyToManyField(blank=True, help_text='Team members (including submitter for team results)', related_name='team_results', to='api.athlete'),
        ),
        migrations.AddField(
            model_name='athleteperformancevideo',
            name='athlete_score',
            field=models.OneToOneField(help_text='The athlete score entry this video documents', on_delete=django.db.models.deletion.CASCADE, related_name='performance_video', to='api.categoryathletescore', verbose_name='Solo category'),
        ),
        migrations.AddField(
            model_name='categoryfieldassignment',
            name='category',
            field=models.OneToOneField(help_text='The category being assigned', on_delete=django.db.models.deletion.CASCADE, related_name='field_assignment', to='api.category'),
        ),
        migrations.AddField(
            model_name='categoryrefereeassignment',
            name='category',
            field=models.OneToOneField(help_text='The category these referees are assigned to', on_delete=django.db.models.deletion.CASCADE, related_name='referee_assignment', to='api.category'),
        ),
        migrations.AddField(
            model_name='categoryrefereeassignment',
            name='referee_1',
            field=models.ForeignKey(blank=True, help_text='Referee 1 (R1)', limit_choices_to={'is_referee': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referee_1_categories', to='api.athlete'),
        ),
        migrations.AddField(
            model_name='categoryrefereeassignment',
            name='referee_2',
            field=models.ForeignKey(blank=True, help_text='Referee 2 (R2)', limit_choices_to={'is_referee': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referee_2_categories', to='api.athlete'),
        ),
        migrations.AddField(
            model_name='categoryrefereeassignment',
            name='referee_3',
            field=models.ForeignKey(blank=True, help_text='Referee 3 (R3)', limit_choices_to={'is_referee': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referee_3_categories', to='api.athlete'),
        ),
        migrations.AddField(
            model_name='categoryrefereeassignment',
            name='referee_4',
            field=models.ForeignKey(blank=True, help_text='Referee 4 (R4)', limit_choices_to={'is_referee': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referee_4_categories', to='api.athlete'),
        ),
        migrations.AddField(
            model_name='categoryrefereeassignment',
            name='referee_5',
            field=models.ForeignKey(blank=True, help_text='Referee 5 (R5)', limit_choices_to={'is_referee': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referee_5_categories', to='api.athlete'),
        ),
        migrations.AddField(
            model_name='categoryrefereescore',
            name='athlete_score',
            field=models.ForeignKey(help_text='The athlete/team result being scored', on_delete=django.db.models.deletion.CASCADE, related_name='referee_scores', to='api.categoryathletescore'),
        ),
        migrations.AddField(
            model_name='categoryrefereescore',
            name='referee',
            field=models.ForeignKey(help_text='The referee providing this score', limit_choices_to={'is_referee': True}, on_delete=django.db.models.deletion.CASCADE, related_name='given_category_scores', to='api.athlete'),
        ),
        migrations.AddField(
            model_name='categoryteam',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_teams', to='api.category'),
        ),
        migrations.AddField(
            model_name='categoryteamscore',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_scores', to='api.category'),
        ),
        migrations.AddField(
            model_name='categoryteamscore',
            name='referee',
            field=models.ForeignKey(limit_choices_to={'is_referee': True}, on_delete=django.db.models.deletion.CASCADE, to='api.athlete'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='athletes', to='api.city'),
        ),
        migrations.AddField(
            model_name='club',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clubs', to='api.city'),
        ),
        migrations.AddField(
            model_name='club',
            name='coaches',
            field=models.ManyToManyField(blank=True, related_name='coached_clubs', to='api.athlete'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='athletes', to='api.club'),
        ),
        migrations.AddField(
            model_name='competitionfield',
            name='event',
            field=models.ForeignKey(help_text='The event this field belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='landing.event'),
        ),
        migrations.AddField(
            model_name='categoryfieldassignment',
            name='field',
            field=models.ForeignKey(help_text='The field this category is assigned to', on_delete=django.db.models.deletion.CASCADE, related_name='category_assignments', to='api.competitionfield'),
        ),
        migrations.AddField(
            model_name='displaymonitorsession',
            name='current_athlete',
            field=models.ForeignKey(blank=True, help_text='The current athlete being displayed (for solo/teams)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitor_sessions', to='api.athlete'),
        ),
        migrations.AddField(
            model_name='displaymonitorsession',
            name='current_category',
            field=models.ForeignKey(blank=True, help_text='The category currently displayed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitor_sessions_category', to='api.category'),
        ),
        migrations.AddField(
            model_name='displaymonitorsession',
            name='field',
            field=models.OneToOneField(help_text='Which field this monitor serves', on_delete=django.db.models.deletion.CASCADE, related_name='monitor_session', to='api.competitionfield'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='federation_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='athletes', to='api.federationrole'),
        ),
        migrations.AddField(
            model_name='fightathleteweight',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fight_weights', to='api.athlete'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='current_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_athletes', to='api.grade'),
        ),
        migrations.AddField(
            model_name='gradehistory',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_history', to='api.athlete'),
        ),
        migrations.AddField(
            model_name='gradehistory',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Optional event associated with this grade exam', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_histories', to='landing.event'),
        ),
        migrations.AddField(
            model_name='gradehistory',
            name='examiner_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades_as_examiner1', to='api.athlete'),
        ),
        migrations.AddField(
            model_name='gradehistory',
            name='examiner_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades_as_examiner2', to='api.athlete'),
        ),
        migrations.AddField(
            model_name='gradehistory',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.grade'),
        ),
        migrations.AddField(
            model_name='gradehistory',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_grades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='landing.event'),
        ),
        migrations.AddField(
            model_name='categoryathletescore',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Group assignment (similar to Category model)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='athlete_scores', to='api.group'),
        ),
        migrations.AddField(
            model_name='category',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='api.group'),
        ),
        migrations.AddField(
            model_name='match',
            name='blue_corner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blue_corner_matches', to='api.athlete'),
        ),
        migrations.AddField(
            model_name='match',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='api.category'),
        ),
        migrations.AddField(
            model_name='match',
            name='central_referee',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_referee': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='central_for_matches', to='api.athlete'),
        ),
        migrations.AddField(
            model_name='match',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='api.competitionfield'),
        ),
        migrations.AddField(
            model_name='match',
            name='red_corner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='red_corner_matches', to='api.athlete'),
        ),
        migrations.AddField(
            model_name='match',
            name='referees',
            field=models.ManyToManyField(limit_choices_to={'is_referee': True}, related_name='refereed_matches', to='api.athlete'),
        ),
        migrations.AddField(
            model_name='displaymonitorsession',
            name='current_match',
            field=models.ForeignKey(blank=True, help_text='The match currently displayed (for fighting categories)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitor_sessions_match', to='api.match'),
        ),
        migrations.AddField(
            model_name='matchfieldassignment',
            name='field',
            field=models.ForeignKey(blank=True, help_text='The field this match is assigned to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_assignments', to='api.competitionfield'),
        ),
        migrations.AddField(
            model_name='matchfieldassignment',
            name='match',
            field=models.OneToOneField(help_text='The match being assigned', on_delete=django.db.models.deletion.CASCADE, related_name='field_assignment', to='api.match'),
        ),
        migrations.AddField(
            model_name='matchrefereeassignment',
            name='match',
            field=models.OneToOneField(help_text='The match these referees are assigned to', on_delete=django.db.models.deletion.CASCADE, related_name='referee_assignment', to='api.match'),
        ),
        migrations.AddField(
            model_name='matchrefereeassignment',
            name='referee_1',
            field=models.ForeignKey(blank=True, help_text='Referee position 1 (R1)', limit_choices_to={'is_referee': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_r1_assignments', to='api.athlete', verbose_name='Referee 1'),
        ),
        migrations.AddField(
            model_name='matchrefereeassignment',
            name='referee_2',
            field=models.ForeignKey(blank=True, help_text='Referee position 2 (R2)', limit_choices_to={'is_referee': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_r2_assignments', to='api.athlete', verbose_name='Referee 2'),
        ),
        migrations.AddField(
            model_name='matchrefereeassignment',
            name='referee_3',
            field=models.ForeignKey(blank=True, help_text='Referee position 3 (R3)', limit_choices_to={'is_referee': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_r3_assignments', to='api.athlete', verbose_name='Referee 3'),
        ),
        migrations.AddField(
            model_name='matchrefereeassignment',
            name='referee_4',
            field=models.ForeignKey(blank=True, help_text='Referee position 4 (R4)', limit_choices_to={'is_referee': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_r4_assignments', to='api.athlete', verbose_name='Referee 4'),
        ),
        migrations.AddField(
            model_name='matchrefereeassignment',
            name='referee_5',
            field=models.ForeignKey(blank=True, help_text='Referee position 5 (R5)', limit_choices_to={'is_referee': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_r5_assignments', to='api.athlete', verbose_name='Referee 5'),
        ),
        migrations.AddField(
            model_name='matchrefereescore',
            name='match',
            field=models.ForeignKey(help_text='The match being scored', on_delete=django.db.models.deletion.CASCADE, related_name='simplified_referee_scores', to='api.match'),
        ),
        migrations.AddField(
            model_name='matchrefereescore',
            name='referee',
            field=models.ForeignKey(help_text='The referee providing this score', limit_choices_to={'is_referee': True}, on_delete=django.db.models.deletion.CASCADE, related_name='given_match_scores', to='api.athlete'),
        ),
        migrations.AddField(
            model_name='matchround',
            name='match',
            field=models.ForeignKey(help_text='The match this round belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='api.match'),
        ),
        migrations.AddField(
            model_name='matchvideorecording',
            name='match',
            field=models.ForeignKey(help_text='The match this video records', on_delete=django.db.models.deletion.CASCADE, related_name='video_recordings', to='api.match'),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.categoryathletescore'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qrcodeassignment',
            name='category',
            field=models.ForeignKey(blank=True, help_text='The category this QR code grants access to (solo/teams only)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_assignments', to='api.category'),
        ),
        migrations.AddField(
            model_name='qrcodeassignment',
            name='match',
            field=models.ForeignKey(blank=True, help_text='The match this QR code grants access to (fighting only)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_assignments', to='api.match'),
        ),
        migrations.AddField(
            model_name='qrcodeassignment',
            name='referee',
            field=models.ForeignKey(help_text='The referee this QR code is for', limit_choices_to={'is_referee': True}, on_delete=django.db.models.deletion.CASCADE, related_name='qr_assignments', to='api.athlete'),
        ),
        migrations.AddField(
            model_name='refereepointevent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refereepointevent',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_events', to='api.match'),
        ),
        migrations.AddField(
            model_name='refereepointevent',
            name='referee',
            field=models.ForeignKey(limit_choices_to={'is_referee': True}, on_delete=django.db.models.deletion.CASCADE, to='api.athlete'),
        ),
        migrations.AddField(
            model_name='refereescore',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referee_scores', to='api.match'),
        ),
        migrations.AddField(
            model_name='refereescore',
            name='referee',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_referee': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.athlete'),
        ),
        migrations.AddField(
            model_name='supporterathleterelation',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporters', to='api.athlete'),
        ),
        migrations.AddField(
            model_name='supporterathleterelation',
            name='supporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supported_athletes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='categories',
            field=models.ManyToManyField(blank=True, limit_choices_to={'type': 'teams'}, related_name='team_categories', through='api.CategoryTeam', to='api.category'),
        ),
        migrations.AddField(
            model_name='categoryteamscore',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_scores', to='api.team'),
        ),
        migrations.AddField(
            model_name='categoryteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_categories', to='api.team'),
        ),
        migrations.AddField(
            model_name='category',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='category_teams', through='api.CategoryTeam', to='api.team'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='api.athlete'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.team'),
        ),
        migrations.AddField(
            model_name='teamperformancevideo',
            name='category_team',
            field=models.OneToOneField(help_text='The team enrollment this video documents', on_delete=django.db.models.deletion.CASCADE, related_name='performance_video', to='api.categoryteam'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='athletes', to='api.title'),
        ),
        migrations.AddField(
            model_name='trainingseminarparticipation',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seminar_participations', to='api.athlete'),
        ),
        migrations.AddField(
            model_name='trainingseminarparticipation',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Event this athlete participated in', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seminar_participations', to='landing.event'),
        ),
        migrations.AddField(
            model_name='trainingseminarparticipation',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_seminar_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingseminarparticipation',
            name='seminar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_participations', to='landing.event'),
        ),
        migrations.CreateModel(
            name='EventParticipation',
            fields=[
            ],
            options={
                'verbose_name': 'Event participation',
                'verbose_name_plural': 'Event participations',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.trainingseminarparticipation',),
        ),
        migrations.AddField(
            model_name='visa',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visas', to='api.athlete'),
        ),
        migrations.AddField(
            model_name='visa',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_visas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FightCategory',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.category')),
                ('first_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fight_first_place_categories', to='api.athlete')),
                ('second_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fight_second_place_categories', to='api.athlete')),
                ('third_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fight_third_place_categories', to='api.athlete')),
            ],
            options={
                'verbose_name': 'Fight Category',
                'verbose_name_plural': 'Fight Categories',
            },
            bases=('api.category',),
        ),
        migrations.AddField(
            model_name='fightathleteweight',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_weights', to='api.fightcategory'),
        ),
        migrations.CreateModel(
            name='SoloCategory',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.category')),
                ('first_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solo_first_place_categories', to='api.athlete')),
                ('second_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solo_second_place_categories', to='api.athlete')),
                ('third_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solo_third_place_categories', to='api.athlete')),
            ],
            options={
                'verbose_name': 'Solo Category',
                'verbose_name_plural': 'Solo Categories',
            },
            bases=('api.category',),
        ),
        migrations.CreateModel(
            name='TeamCategory',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.category')),
                ('first_place_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_place_team_categories', to='api.team')),
                ('second_place_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_place_team_categories', to='api.team')),
                ('third_place_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_place_team_categories', to='api.team')),
            ],
            options={
                'verbose_name': 'Team Category',
                'verbose_name_plural': 'Team Categories',
            },
            bases=('api.category',),
        ),
        migrations.AddIndex(
            model_name='categoryathlete',
            index=models.Index(fields=['category'], name='api_categor_categor_1965b6_idx'),
        ),
        migrations.AddIndex(
            model_name='categoryathlete',
            index=models.Index(fields=['athlete'], name='api_categor_athlete_ab304c_idx'),
        ),
        migrations.AddIndex(
            model_name='categoryathlete',
            index=models.Index(fields=['category', 'disqualified'], name='api_categor_categor_bbd9cd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='categoryathlete',
            unique_together={('category', 'athlete')},
        ),
        migrations.AddIndex(
            model_name='categoryrefereescore',
            index=models.Index(fields=['athlete_score', 'referee'], name='api_categor_athlete_0191ff_idx'),
        ),
        migrations.AddIndex(
            model_name='categoryrefereescore',
            index=models.Index(fields=['submitted_date'], name='api_categor_submitt_203629_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='categoryrefereescore',
            unique_together={('athlete_score', 'referee')},
        ),
        migrations.AlterUniqueTogether(
            name='competitionfield',
            unique_together={('event', 'field_number')},
        ),
        migrations.AddIndex(
            model_name='categoryfieldassignment',
            index=models.Index(fields=['field', 'status'], name='api_categor_field_i_4b9e7b_idx'),
        ),
        migrations.AddIndex(
            model_name='gradehistory',
            index=models.Index(fields=['athlete', 'status'], name='api_gradehi_athlete_c6e8ab_idx'),
        ),
        migrations.AddIndex(
            model_name='gradehistory',
            index=models.Index(fields=['obtained_date'], name='api_gradehi_obtaine_c3f085_idx'),
        ),
        migrations.AddIndex(
            model_name='gradehistory',
            index=models.Index(fields=['status', 'submitted_date'], name='api_gradehi_status_75fb45_idx'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(condition=models.Q(('event__isnull', False)), fields=('event', 'name'), name='unique_group_per_event'),
        ),
        migrations.AddIndex(
            model_name='categoryathletescore',
            index=models.Index(fields=['category', 'status'], name='api_categor_categor_2b2894_idx'),
        ),
        migrations.AddIndex(
            model_name='categoryathletescore',
            index=models.Index(fields=['athlete', 'status'], name='api_categor_athlete_01b156_idx'),
        ),
        migrations.AddIndex(
            model_name='categoryathletescore',
            index=models.Index(fields=['submitted_date'], name='api_categor_submitt_79723d_idx'),
        ),
        migrations.AddIndex(
            model_name='categoryathletescore',
            index=models.Index(fields=['status', 'submitted_by_athlete'], name='api_categor_status_a48fcd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='categoryathletescore',
            unique_together={('category', 'athlete', 'referee')},
        ),
        migrations.AddIndex(
            model_name='matchfieldassignment',
            index=models.Index(fields=['field', 'status'], name='api_match_field_status_idx'),
        ),
        migrations.AddIndex(
            model_name='matchrefereescore',
            index=models.Index(fields=['match', 'referee'], name='api_matchre_match_i_808162_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='matchrefereescore',
            unique_together={('match', 'referee')},
        ),
        migrations.AlterUniqueTogether(
            name='matchround',
            unique_together={('match', 'round_number')},
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', '-created_at'], name='api_notific_recipie_5c719b_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='api_notific_recipie_28b188_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcodeassignment',
            index=models.Index(fields=['code'], name='api_qrcodea_code_211aa9_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcodeassignment',
            index=models.Index(fields=['referee', 'category'], name='api_qrcodea_referee_bb0f8d_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcodeassignment',
            index=models.Index(fields=['referee', 'match'], name='api_qrcodea_referee_f3c5c7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='qrcodeassignment',
            unique_together={('referee', 'category', 'match')},
        ),
        migrations.AlterUniqueTogether(
            name='supporterathleterelation',
            unique_together={('supporter', 'athlete')},
        ),
        migrations.AlterUniqueTogether(
            name='categoryteamscore',
            unique_together={('category', 'team', 'referee')},
        ),
        migrations.AddIndex(
            model_name='categoryteam',
            index=models.Index(fields=['category'], name='api_categor_categor_31d214_idx'),
        ),
        migrations.AddIndex(
            model_name='categoryteam',
            index=models.Index(fields=['team'], name='api_categor_team_id_f2b4d6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='categoryteam',
            unique_together={('category', 'team')},
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['event'], name='api_categor_event_i_67e574_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together={('team', 'athlete')},
        ),
        migrations.AddIndex(
            model_name='athlete',
            index=models.Index(fields=['club', 'status'], name='api_athlete_club_id_7f309f_idx'),
        ),
        migrations.AddIndex(
            model_name='athlete',
            index=models.Index(fields=['current_grade'], name='api_athlete_current_a89674_idx'),
        ),
        migrations.AddIndex(
            model_name='athlete',
            index=models.Index(fields=['is_coach'], name='api_athlete_is_coac_708bf5_idx'),
        ),
        migrations.AddIndex(
            model_name='athlete',
            index=models.Index(fields=['is_referee'], name='api_athlete_is_refe_007646_idx'),
        ),
        migrations.AddIndex(
            model_name='athlete',
            index=models.Index(fields=['status', 'submitted_date'], name='api_athlete_status_d66a16_idx'),
        ),
        migrations.AddIndex(
            model_name='athlete',
            index=models.Index(fields=['user'], name='api_athlete_user_id_b0981f_idx'),
        ),
        migrations.AddIndex(
            model_name='athlete',
            index=models.Index(fields=['city'], name='api_athlete_city_id_f33040_idx'),
        ),
        migrations.AddIndex(
            model_name='athlete',
            index=models.Index(fields=['registered_date'], name='api_athlete_registe_2fffc4_idx'),
        ),
        migrations.AddIndex(
            model_name='athlete',
            index=models.Index(fields=['created_at'], name='api_athlete_created_ba7c00_idx'),
        ),
        migrations.AddIndex(
            model_name='athlete',
            index=models.Index(fields=['club', 'is_coach'], name='api_athlete_club_id_9d2ce8_idx'),
        ),
        migrations.AddIndex(
            model_name='athlete',
            index=models.Index(fields=['club', 'status', 'is_referee'], name='api_athlete_club_id_26bca6_idx'),
        ),
        migrations.AddIndex(
            model_name='athlete',
            index=models.Index(fields=['status', 'approved_date'], name='api_athlete_status_1c7bad_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingseminarparticipation',
            index=models.Index(fields=['athlete', 'status'], name='api_trainin_athlete_21adfb_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingseminarparticipation',
            index=models.Index(fields=['status', 'submitted_date'], name='api_trainin_status_df32f7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='trainingseminarparticipation',
            unique_together={('athlete', 'event')},
        ),
        migrations.AddIndex(
            model_name='visa',
            index=models.Index(fields=['athlete', 'visa_type', 'issued_date'], name='api_visa_athlete_4fcb59_idx'),
        ),
        migrations.AddIndex(
            model_name='visa',
            index=models.Index(fields=['athlete', 'visa_type', '-issued_date'], name='api_visa_athlete_c46c69_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='visa',
            unique_together={('athlete', 'visa_type', 'issued_date')},
        ),
        migrations.AlterUniqueTogether(
            name='fightathleteweight',
            unique_together={('category', 'athlete')},
        ),
    ]
