# Generated by Django 5.2.1 on 2025-10-21 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_athletes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='athlete',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='athlete', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.city'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('athlete', 'Athlete'), ('supporter', 'Supporter'), ('user', 'User')], default='user', max_length=10),
        ),
        migrations.CreateModel(
            name='AthleteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField(blank=True, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('previous_experience', models.TextField(blank=True, help_text='Previous martial arts experience', null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revision_required', 'Revision Required')], default='pending', max_length=20)),
                ('submitted_date', models.DateTimeField(auto_now_add=True)),
                ('reviewed_date', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes about approval/rejection', null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='pending_profiles/')),
                ('medical_certificate', models.FileField(blank=True, null=True, upload_to='pending_medical/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('approved_athlete', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.athlete')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.city')),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.club')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_profiles', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Athlete Profile (Pending)',
                'verbose_name_plural': 'Athlete Profiles (Pending)',
                'ordering': ['-submitted_date'],
            },
        ),
        migrations.CreateModel(
            name='AthleteProfileActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submitted', 'Profile Submitted'), ('approved', 'Profile Approved'), ('rejected', 'Profile Rejected'), ('revision_requested', 'Revision Requested'), ('updated', 'Profile Updated'), ('resubmitted', 'Profile Resubmitted')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_log', to='api.athleteprofile')),
            ],
            options={
                'verbose_name': 'Profile Activity',
                'verbose_name_plural': 'Profile Activities',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SupporterAthleteRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('parent', 'Parent'), ('guardian', 'Legal Guardian'), ('coach', 'Coach'), ('other', 'Other')], default='parent', max_length=20)),
                ('can_edit', models.BooleanField(default=True)),
                ('can_register_competitions', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporters', to='api.athlete')),
                ('supporter', models.ForeignKey(limit_choices_to={'role': 'supporter'}, on_delete=django.db.models.deletion.CASCADE, related_name='managed_athletes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supporter-Athlete Relationship',
                'verbose_name_plural': 'Supporter-Athlete Relationships',
                'unique_together': {('supporter', 'athlete')},
            },
        ),
    ]
