# Generated by Django 6.0.2 on 2026-03-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_landing_event_fks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['display_order', 'id'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['event', 'display_order', 'id']},
        ),
        migrations.AddField(
            model_name='category',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Order within the group for display purposes'),
        ),
        migrations.AddField(
            model_name='group',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Order within the event for display purposes'),
        ),
    ]
