# Generated by Django 5.2.1 on 2025-10-21 19:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_athlete_approved_by_athlete_approved_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Admin notes about approval/rejection', null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='medical_certificate',
            field=models.FileField(blank=True, null=True, upload_to='medical_certificates/'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='previous_experience',
            field=models.TextField(blank=True, help_text='Previous martial arts experience', null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_athletes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='athlete',
            name='reviewed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revision_required', 'Revision Required')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='athlete',
            name='submitted_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AthleteActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submitted', 'Profile Submitted'), ('approved', 'Profile Approved'), ('rejected', 'Profile Rejected'), ('revision_requested', 'Revision Requested'), ('updated', 'Profile Updated'), ('resubmitted', 'Profile Resubmitted')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_log', to='api.athlete')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Athlete Activity',
                'verbose_name_plural': 'Athlete Activities',
                'ordering': ['-timestamp'],
            },
        ),
    ]
