# Generated by Django 6.0.2 on 2026-03-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_display_order_to_group_and_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.AddField(
            model_name='club',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Order for display in centralizator'),
        ),
    ]
