# Generated by Django 5.2.1 on 2025-10-21 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_consolidate_athlete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athleteprofileactivity',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='athleteprofileactivity',
            name='performed_by',
        ),
        migrations.AlterModelOptions(
            name='supporterathleterelation',
            options={},
        ),
        migrations.AlterField(
            model_name='supporterathleterelation',
            name='can_edit',
            field=models.BooleanField(default=False, help_text='Can edit athlete profile'),
        ),
        migrations.AlterField(
            model_name='supporterathleterelation',
            name='can_register_competitions',
            field=models.BooleanField(default=False, help_text='Can register athlete for competitions'),
        ),
        migrations.AlterField(
            model_name='supporterathleterelation',
            name='relationship',
            field=models.CharField(choices=[('parent', 'Parent'), ('guardian', 'Guardian'), ('coach', 'Coach'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='supporterathleterelation',
            name='supporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supported_athletes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AthleteResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition_name', models.CharField(help_text='Name of the competition', max_length=200)),
                ('competition_date', models.DateField(help_text='Date of the competition')),
                ('competition_location', models.CharField(help_text='Location/venue of the competition', max_length=200)),
                ('result_type', models.CharField(choices=[('competition', 'Competition Result'), ('tournament', 'Tournament Result'), ('championship', 'Championship Result'), ('other', 'Other Achievement')], default='competition', max_length=20)),
                ('category', models.CharField(help_text='Competition category (e.g., "Men\'s Kata", "Women\'s Kumite")', max_length=100)),
                ('placement', models.CharField(help_text='Final placement (e.g., "1st Place", "2nd Place", "Semi-finalist")', max_length=50)),
                ('points_score', models.DecimalField(blank=True, decimal_places=2, help_text='Points or score achieved', max_digits=6, null=True)),
                ('opponent_info', models.TextField(blank=True, help_text='Information about opponents faced', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the performance', null=True)),
                ('certificate_image', models.ImageField(blank=True, help_text='Certificate or award photo', null=True, upload_to='result_certificates/')),
                ('result_document', models.FileField(blank=True, help_text='Official result document', null=True, upload_to='result_documents/')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revision_required', 'Revision Required')], default='pending', max_length=20)),
                ('submitted_date', models.DateTimeField(auto_now_add=True)),
                ('reviewed_date', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes about approval/rejection', null=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_results', to='api.athlete')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Athlete Result',
                'verbose_name_plural': 'Athlete Results',
                'ordering': ['-competition_date', '-submitted_date'],
            },
        ),
        migrations.CreateModel(
            name='AthleteResultActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submitted', 'Result Submitted'), ('approved', 'Result Approved'), ('rejected', 'Result Rejected'), ('revision_requested', 'Revision Requested'), ('updated', 'Result Updated'), ('resubmitted', 'Result Resubmitted'), ('deleted', 'Result Deleted')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_log', to='api.athleteresult')),
            ],
            options={
                'verbose_name': 'Result Activity',
                'verbose_name_plural': 'Result Activities',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='AthleteProfile',
        ),
        migrations.DeleteModel(
            name='AthleteProfileActivity',
        ),
    ]
