# Generated by Django 6.0.2 on 2026-03-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_add_club_display_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='birth_date_end',
            field=models.DateField(blank=True, help_text='Exact end date for age eligibility (inclusive). If set, takes priority over birth_year_end.', null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='birth_date_start',
            field=models.DateField(blank=True, help_text='Exact start date for age eligibility (inclusive). If set, takes priority over birth_year_start.', null=True),
        ),
    ]
