# Generated by Django 6.0.2 on 2026-03-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_group_date_range_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='allow_younger',
            field=models.BooleanField(default=False, help_text='Allow athletes younger than the minimum age (who want to compete in a higher age category)'),
        ),
    ]
