# Generated by Django 5.2.1 on 2025-10-21 20:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_athleteresultactivity_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualvisa',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Admin notes about approval/rejection', null=True),
        ),
        migrations.AddField(
            model_name='annualvisa',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the annual visa', null=True),
        ),
        migrations.AddField(
            model_name='annualvisa',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_annual_visas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='annualvisa',
            name='reviewed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annualvisa',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revision_required', 'Revision Required')], default='approved', help_text='Approval status (defaults to approved for admin submissions)', max_length=20),
        ),
        migrations.AddField(
            model_name='annualvisa',
            name='submitted_by_athlete',
            field=models.BooleanField(default=False, help_text='True if submitted by the athlete themselves'),
        ),
        migrations.AddField(
            model_name='annualvisa',
            name='submitted_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='annualvisa',
            name='visa_document',
            field=models.FileField(blank=True, help_text='Annual visa document', null=True, upload_to='visa_documents/'),
        ),
        migrations.AddField(
            model_name='annualvisa',
            name='visa_image',
            field=models.ImageField(blank=True, help_text='Annual visa certificate photo', null=True, upload_to='visa_images/'),
        ),
        migrations.AddField(
            model_name='gradehistory',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Admin notes about approval/rejection', null=True),
        ),
        migrations.AddField(
            model_name='gradehistory',
            name='certificate_image',
            field=models.ImageField(blank=True, help_text='Grade certificate photo', null=True, upload_to='grade_certificates/'),
        ),
        migrations.AddField(
            model_name='gradehistory',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the grading exam', null=True),
        ),
        migrations.AddField(
            model_name='gradehistory',
            name='result_document',
            field=models.FileField(blank=True, help_text='Official grade document', null=True, upload_to='grade_documents/'),
        ),
        migrations.AddField(
            model_name='gradehistory',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_grades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gradehistory',
            name='reviewed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gradehistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revision_required', 'Revision Required')], default='approved', help_text='Approval status (defaults to approved for admin submissions)', max_length=20),
        ),
        migrations.AddField(
            model_name='gradehistory',
            name='submitted_by_athlete',
            field=models.BooleanField(default=False, help_text='True if submitted by the athlete themselves'),
        ),
        migrations.AddField(
            model_name='gradehistory',
            name='submitted_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalvisa',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Admin notes about approval/rejection', null=True),
        ),
        migrations.AddField(
            model_name='medicalvisa',
            name='medical_document',
            field=models.FileField(blank=True, help_text='Medical examination document', null=True, upload_to='medical_documents/'),
        ),
        migrations.AddField(
            model_name='medicalvisa',
            name='medical_image',
            field=models.ImageField(blank=True, help_text='Medical certificate photo', null=True, upload_to='medical_images/'),
        ),
        migrations.AddField(
            model_name='medicalvisa',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the medical examination', null=True),
        ),
        migrations.AddField(
            model_name='medicalvisa',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_medical_visas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalvisa',
            name='reviewed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalvisa',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revision_required', 'Revision Required')], default='approved', help_text='Approval status (defaults to approved for admin submissions)', max_length=20),
        ),
        migrations.AddField(
            model_name='medicalvisa',
            name='submitted_by_athlete',
            field=models.BooleanField(default=False, help_text='True if submitted by the athlete themselves'),
        ),
        migrations.AddField(
            model_name='medicalvisa',
            name='submitted_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AthleteMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent_name', models.CharField(help_text='Name of the opponent', max_length=200)),
                ('match_date', models.DateField(help_text='Date of the match')),
                ('venue', models.CharField(blank=True, help_text='Venue where the match took place', max_length=200, null=True)),
                ('result', models.CharField(choices=[('win', 'Win'), ('loss', 'Loss'), ('draw', 'Draw')], help_text='Match result', max_length=10)),
                ('round_ended', models.CharField(blank=True, help_text='Round when match ended (e.g., "Round 2", "Decision")', max_length=50, null=True)),
                ('submitted_by_athlete', models.BooleanField(default=False, help_text='True if submitted by the athlete themselves')),
                ('match_video', models.FileField(blank=True, help_text='Video of the match', null=True, upload_to='match_videos/')),
                ('match_image', models.ImageField(blank=True, help_text='Photo from the match', null=True, upload_to='match_images/')),
                ('result_document', models.FileField(blank=True, help_text='Official match result document', null=True, upload_to='match_documents/')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the match', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revision_required', 'Revision Required')], default='approved', help_text='Approval status (defaults to approved for admin submissions)', max_length=20)),
                ('submitted_date', models.DateTimeField(auto_now_add=True)),
                ('reviewed_date', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes about approval/rejection', null=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_matches', to='api.athlete')),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='athlete_matches', to='api.competition')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_athlete_matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Athlete Match',
                'verbose_name_plural': 'Athlete Matches',
                'ordering': ['-match_date'],
            },
        ),
        migrations.CreateModel(
            name='TrainingSeminarParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_by_athlete', models.BooleanField(default=False, help_text='True if submitted by the athlete themselves')),
                ('participation_certificate', models.ImageField(blank=True, help_text='Participation certificate photo', null=True, upload_to='seminar_certificates/')),
                ('participation_document', models.FileField(blank=True, help_text='Official participation document', null=True, upload_to='seminar_documents/')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about participation', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revision_required', 'Revision Required')], default='approved', help_text='Approval status (defaults to approved for admin submissions)', max_length=20)),
                ('submitted_date', models.DateTimeField(auto_now_add=True)),
                ('reviewed_date', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes about approval/rejection', null=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seminar_participations', to='api.athlete')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_seminar_participations', to=settings.AUTH_USER_MODEL)),
                ('seminar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='api.trainingseminar')),
            ],
            options={
                'unique_together': {('athlete', 'seminar')},
            },
        ),
    ]
