# Generated by Django 5.2.1 on 2025-10-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_annualvisa_admin_notes_annualvisa_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryathletescore',
            name='placement_claimed',
            field=models.CharField(blank=True, choices=[('1st', '1st Place'), ('2nd', '2nd Place'), ('3rd', '3rd Place')], help_text='Award placement claimed by athlete', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='categoryathletescore',
            name='score',
            field=models.IntegerField(default=0, help_text='Score given by referee (not required for athlete submissions)'),
        ),
    ]
