# Generated by Django 6.0.2 on 2026-03-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_group_allow_younger'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryfieldassignment',
            name='estimated_duration',
            field=models.IntegerField(default=15, help_text='Estimated duration in minutes'),
        ),
        migrations.AddField(
            model_name='matchfieldassignment',
            name='estimated_duration',
            field=models.IntegerField(default=10, help_text='Estimated duration in minutes'),
        ),
    ]
