# Generated by Django 5.2.1 on 2025-10-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_categoryathletescore_placement_claimed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryathletescore',
            name='score',
            field=models.IntegerField(blank=True, default=0, help_text='Numeric score given by referee/official (not relevant for athlete self-submissions with placement claims)', null=True),
        ),
    ]
