# Generated by Django 6.0.2 on 2026-03-06 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_estimated_duration'),
        ('landing', '0008_alter_newscomment_options_alter_newspost_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionfield',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Planned start time for this field (e.g., 09:00)', null=True),
        ),
        migrations.CreateModel(
            name='CompetitionReferee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('head_referee', 'Arbitru Șef'), ('referee', 'Arbitru'), ('reserve', 'Rezervă')], default='referee', help_text='Role in the competition', max_length=30)),
                ('notes', models.TextField(blank=True, default='', help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete', models.ForeignKey(help_text='The referee athlete', limit_choices_to={'is_referee': True}, on_delete=django.db.models.deletion.CASCADE, related_name='competition_referee_entries', to='api.athlete')),
                ('event', models.ForeignKey(help_text='The event this referee is participating in', on_delete=django.db.models.deletion.CASCADE, related_name='competition_referees', to='landing.event')),
            ],
            options={
                'verbose_name': 'Competition Referee',
                'verbose_name_plural': 'Competition Referees',
                'ordering': ['role', 'athlete__last_name'],
                'unique_together': {('event', 'athlete')},
            },
        ),
    ]
