# Generated by Django 5.2.1 on 2025-10-22 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_categoryathletescore_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTeamAthleteScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement_claimed', models.CharField(choices=[('1st', '1st Place'), ('2nd', '2nd Place'), ('3rd', '3rd Place')], help_text='Award placement claimed for the team', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the team performance', null=True)),
                ('certificate_image', models.ImageField(blank=True, help_text='Team certificate or award photo', null=True, upload_to='team_result_certificates/')),
                ('result_document', models.FileField(blank=True, help_text='Official team result document', null=True, upload_to='team_result_documents/')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revision_required', 'Revision Required')], default='pending', help_text='Approval status', max_length=20)),
                ('submitted_date', models.DateTimeField(auto_now_add=True)),
                ('reviewed_date', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes about approval/rejection', null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_athlete_scores', to='api.category')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_team_scores', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(help_text='Athlete who submitted this team result', on_delete=django.db.models.deletion.CASCADE, related_name='submitted_team_results', to='api.athlete')),
                ('team_members', models.ManyToManyField(help_text='Athletes who were part of this team', related_name='team_results', to='api.athlete')),
            ],
            options={
                'verbose_name': 'Team Athlete Score',
                'verbose_name_plural': 'Team Athlete Scores',
                'ordering': ['-submitted_date'],
            },
        ),
    ]
