# Generated by Django 6.0.2 on 2026-03-06 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_competitionfield_start_time_competitionreferee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competitionreferee',
            options={'ordering': ['athlete__last_name'], 'verbose_name': 'Competition Referee', 'verbose_name_plural': 'Competition Referees'},
        ),
        migrations.RemoveField(
            model_name='competitionreferee',
            name='role',
        ),
    ]
