# Generated by Django 6.0.2 on 2026-03-06 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_competitionreferee_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Pauză', help_text='Label for the break (e.g., "Pauză de masă")', max_length=100)),
                ('duration', models.IntegerField(default=60, help_text='Duration in minutes')),
                ('order', models.IntegerField(default=0, help_text='Order position in the field schedule (mixed with category/match assignments)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(help_text='The field this break belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='api.competitionfield')),
            ],
            options={
                'verbose_name': 'Field Break',
                'verbose_name_plural': 'Field Breaks',
                'ordering': ['order'],
            },
        ),
    ]
