# Generated by Django 5.2.1 on 2025-10-23 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_categoryathletescore_result_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryathletescore',
            name='result_type',
        ),
        migrations.AddField(
            model_name='categoryathletescore',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Group assignment (similar to Category model)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='athlete_scores', to='api.group'),
        ),
        migrations.AddField(
            model_name='categoryathletescore',
            name='type',
            field=models.CharField(choices=[('solo', 'Solo'), ('teams', 'Teams'), ('fight', 'Fight')], default='solo', help_text='Type of result: solo, fight, or teams', max_length=10),
        ),
    ]
