# Generated by Django 6.0.2 on 2026-03-06 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_fieldbreak'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='bracket_position',
            field=models.PositiveIntegerField(default=0, help_text='Position within the round (0-based, for visual layout)'),
        ),
        migrations.AddField(
            model_name='match',
            name='next_match',
            field=models.ForeignKey(blank=True, help_text='Winner advances to this match', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_matches', to='api.match'),
        ),
        migrations.AddField(
            model_name='match',
            name='round_number',
            field=models.PositiveIntegerField(default=1, help_text='Round number within the bracket (1=first round, 2=second, etc.)'),
        ),
        migrations.AlterField(
            model_name='match',
            name='blue_corner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blue_corner_matches', to='api.athlete'),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_type',
            field=models.CharField(choices=[('qualifications', 'Qualifications'), ('quarter-finals', 'Quarter-Finals'), ('semi-finals', 'Semi-Finals'), ('finals', 'Finals'), ('bronze', 'Bronze Match')], default='qualifications', max_length=20),
        ),
        migrations.AlterField(
            model_name='match',
            name='red_corner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='red_corner_matches', to='api.athlete'),
        ),
    ]
