# Generated by Django 6.0.2 on 2026-03-06 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_match_bracket_position_match_next_match_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='loser_next_match',
            field=models.ForeignKey(blank=True, help_text='Loser advances to this match (consolation/bronze)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_loser_matches', to='api.match'),
        ),
    ]
