# Generated by Django 5.2.1 on 2025-10-23 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_update_categoryathletescore_type_and_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_on_result_status_change', models.BooleanField(default=True)),
                ('email_on_competition_updates', models.BooleanField(default=True)),
                ('email_on_system_announcements', models.BooleanField(default=True)),
                ('notify_result_submitted', models.BooleanField(default=True)),
                ('notify_result_approved', models.BooleanField(default=True)),
                ('notify_result_rejected', models.BooleanField(default=True)),
                ('notify_result_revision_required', models.BooleanField(default=True)),
                ('notify_competition_created', models.BooleanField(default=True)),
                ('notify_competition_updated', models.BooleanField(default=False)),
                ('notify_system_announcements', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('result_submitted', 'Result Submitted'), ('result_approved', 'Result Approved'), ('result_rejected', 'Result Rejected'), ('result_revision_required', 'Result Revision Required'), ('competition_created', 'Competition Created'), ('competition_updated', 'Competition Updated'), ('system_announcement', 'System Announcement')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('action_data', models.JSONField(blank=True, help_text='Additional data for notification actions', null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.competition')),
                ('related_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.categoryathletescore')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='api_notific_recipie_5c719b_idx'), models.Index(fields=['recipient', 'is_read'], name='api_notific_recipie_28b188_idx')],
            },
        ),
    ]
