# Generated by Django 5.2.1 on 2026-03-06 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_add_loser_next_match_to_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='min_grade',
            field=models.ForeignKey(blank=True, help_text='Minimum grade required to participate in this group (by rank_order). Athletes with a lower grade are excluded.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='min_grade_groups', to='api.grade'),
        ),
    ]
