# Generated by Django 5.2.1 on 2025-10-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_notificationsettings_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsettings',
            name='notify_grade_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='notify_grade_rejected',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='notify_grade_revision_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='notify_grade_submitted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='notify_seminar_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='notify_seminar_rejected',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='notify_seminar_revision_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='notify_seminar_submitted',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('result_submitted', 'Result Submitted'), ('result_approved', 'Result Approved'), ('result_rejected', 'Result Rejected'), ('result_revision_required', 'Result Revision Required'), ('grade_submitted', 'Grade Exam Submitted'), ('grade_approved', 'Grade Exam Approved'), ('grade_rejected', 'Grade Exam Rejected'), ('grade_revision_required', 'Grade Exam Revision Required'), ('seminar_submitted', 'Seminar Participation Submitted'), ('seminar_approved', 'Seminar Participation Approved'), ('seminar_rejected', 'Seminar Participation Rejected'), ('seminar_revision_required', 'Seminar Participation Revision Required'), ('competition_created', 'Competition Created'), ('competition_updated', 'Competition Updated'), ('system_announcement', 'System Announcement')], max_length=30),
        ),
    ]
