# Generated by Django 5.2.1 on 2026-03-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_group_min_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='min_grade',
        ),
        migrations.AddField(
            model_name='group',
            name='allowed_grade_type',
            field=models.CharField(choices=[('all', 'All grades'), ('inferior', 'Inferior grades only'), ('superior', 'Superior grades only')], default='all', help_text="Restrict participation by grade type. 'inferior' = only inferior grades, 'superior' = only superior grades.", max_length=10),
        ),
    ]
