# Generated by Django 5.2.1 on 2026-03-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_group_min_grade_group_allowed_grade_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='birth_year_end',
            field=models.IntegerField(blank=True, help_text='Optional sub-range end (newest birth year). Used for fight categories within a group.', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='birth_year_start',
            field=models.IntegerField(blank=True, help_text='Optional sub-range start (oldest birth year). Used for fight categories within a group.', null=True),
        ),
    ]
