# Generated by Django 6.0.2 on 2026-03-06 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_category_birth_year_end_category_birth_year_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchround',
            name='accumulated_pause_seconds',
            field=models.IntegerField(default=0, help_text='Total seconds spent paused in this round'),
        ),
        migrations.AddField(
            model_name='matchround',
            name='extra_seconds',
            field=models.IntegerField(default=0, help_text='Extra seconds added/removed by admin during this round'),
        ),
        migrations.AddField(
            model_name='matchround',
            name='paused_at',
            field=models.DateTimeField(blank=True, help_text='When the round was paused (null = not paused)', null=True),
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('warning_red', 'Warning Red Corner'), ('warning_blue', 'Warning Blue Corner'), ('penalty_red', 'Penalty Red Corner (-2)'), ('penalty_blue', 'Penalty Blue Corner (-2)'), ('pause', 'Pause'), ('resume', 'Resume'), ('time_add', 'Time Added'), ('time_remove', 'Time Removed')], help_text='Type of event', max_length=20)),
                ('corner', models.CharField(choices=[('red', 'Red Corner'), ('blue', 'Blue Corner'), ('none', 'No Corner')], default='none', help_text='Which corner this event applies to', max_length=10)),
                ('value', models.IntegerField(default=0, help_text='Numeric value (e.g., seconds added/removed, penalty points)')),
                ('notes', models.CharField(blank=True, default='', help_text='Optional notes about the event', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Who created this event (usually central referee or admin)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_match_events', to='api.athlete')),
                ('match', models.ForeignKey(help_text='The match this event belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.match')),
                ('round', models.ForeignKey(blank=True, help_text='The round this event occurred in', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.matchround')),
            ],
            options={
                'verbose_name': 'Match Event',
                'verbose_name_plural': 'Match Events',
                'ordering': ['created_at'],
            },
        ),
    ]
