# Generated by Django 5.2.1 on 2026-03-07 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_matchround_accumulated_pause_seconds_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matchrefereescore',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='matchrefereescore',
            name='round',
            field=models.ForeignKey(blank=True, help_text='The round being scored (null = final/overall decision)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referee_scores', to='api.matchround'),
        ),
        migrations.AlterUniqueTogether(
            name='matchrefereescore',
            unique_together={('match', 'referee', 'round')},
        ),
    ]
