# Generated by Django 5.2.1 on 2026-03-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_matchrefereescore_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchevent',
            name='event_type',
            field=models.CharField(choices=[('warning_red', 'Warning Red Corner'), ('warning_blue', 'Warning Blue Corner'), ('penalty_red', 'Penalty Red Corner'), ('penalty_blue', 'Penalty Blue Corner'), ('bonus_red', 'Bonus Red Corner'), ('bonus_blue', 'Bonus Blue Corner'), ('pause', 'Pause'), ('resume', 'Resume'), ('time_add', 'Time Added'), ('time_remove', 'Time Removed')], help_text='Type of event', max_length=20),
        ),
    ]
