# Generated by Django 5.2.1 on 2025-11-05 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_exam_place'),
        ('landing', '0003_add_newscomment_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradehistory',
            name='exam_date',
        ),
        migrations.AddField(
            model_name='gradehistory',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Optional event associated with this grade exam', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_histories', to='landing.event'),
        ),
    ]
