# Generated by Django 5.2.1 on 2026-03-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_add_bonus_event_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', help_text='Current status of the match', max_length=20),
        ),
        migrations.AlterField(
            model_name='matchevent',
            name='event_type',
            field=models.CharField(choices=[('warning_red', 'Warning Red Corner'), ('warning_blue', 'Warning Blue Corner'), ('penalty_red', 'Penalty Red Corner'), ('penalty_blue', 'Penalty Blue Corner'), ('bonus_red', 'Bonus Red Corner'), ('bonus_blue', 'Bonus Blue Corner'), ('infraction_red', 'Infraction Red Corner'), ('infraction_blue', 'Infraction Blue Corner'), ('disqualify_red', 'Disqualify Red Corner'), ('disqualify_blue', 'Disqualify Blue Corner'), ('pause', 'Pause'), ('resume', 'Resume'), ('time_add', 'Time Added'), ('time_remove', 'Time Removed')], help_text='Type of event', max_length=20),
        ),
    ]
