# Generated by Django 5.2.1 on 2025-11-05 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_gradehistory_exam_date_gradehistory_event'),
        ('landing', '0007_event_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='landing.event'),
        ),
    ]
