# Generated by Django 5.2.1 on 2026-03-07 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_add_match_status_and_infraction_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displaymonitorsession',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('displaying', 'Displaying'), ('scores_revealed', 'Scores Revealed'), ('decisions_revealed', 'Decisions Revealed')], default='idle', help_text='Current display status', max_length=20),
        ),
    ]
