# Generated by Django 6.0.2 on 2026-03-07 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_add_break_timer_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displaymonitorsession',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('displaying', 'Displaying'), ('scores_revealed', 'Scores Revealed'), ('decisions_revealed', 'Decisions Revealed'), ('winner_revealed', 'Winner Revealed')], default='idle', help_text='Current display status', max_length=20),
        ),
    ]
