# Generated by Django 6.0.2 on 2026-03-08 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_displaymonitorsession_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefereePresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_ping', models.DateTimeField(help_text='Last time the referee pinged from the scoring page')),
                ('category', models.ForeignKey(help_text='The category the referee is scoring', on_delete=django.db.models.deletion.CASCADE, related_name='referee_presences', to='api.category')),
                ('referee', models.ForeignKey(help_text='The referee athlete', on_delete=django.db.models.deletion.CASCADE, related_name='presence_records', to='api.athlete')),
            ],
            options={
                'verbose_name': 'Referee Presence',
                'verbose_name_plural': 'Referee Presences',
                'unique_together': {('category', 'referee')},
            },
        ),
    ]
