# Generated by Django 5.2.1 on 2025-11-05 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_migrate_trainingseminars_to_events'),
        ('landing', '0007_event_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingseminarparticipation',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Linked Event after migration (nullable, added for staged migration)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seminar_participations', to='landing.event'),
        ),
    ]
