# Generated by Django 5.2.1 on 2025-11-06 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_add_unique_constraint_gradehistory'),
        ('landing', '0008_alter_newscomment_options_alter_newspost_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrainingSeminarBackup',
        ),
        migrations.CreateModel(
            name='EventProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('landing.event',),
        ),
        migrations.RemoveConstraint(
            model_name='gradehistory',
            name='unique_athlete_grade',
        ),
    ]
