# Generated by Django 5.2.12 on 2026-03-11 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_match_display_mode'),
        ('landing', '0012_event_sync_history_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diplomatemplate',
            options={'ordering': ['event_id', 'category_scope', 'template_kind', 'id']},
        ),
        migrations.AddField(
            model_name='refereepointevent',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refereepointevent',
            name='validation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('validated', 'Validated'), ('rejected', 'Rejected')], default='validated', max_length=20),
        ),
        migrations.AddField(
            model_name='refereepointevent',
            name='video_offset_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FieldRecordingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('recording', 'Recording'), ('stopped', 'Stopped'), ('failed', 'Failed')], default='recording', max_length=20)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('obs_scene_name', models.CharField(blank=True, max_length=255)),
                ('obs_source_name', models.CharField(blank=True, max_length=255)),
                ('recording_file_name', models.CharField(blank=True, max_length=255)),
                ('recording_file_path', models.CharField(blank=True, max_length=500)),
                ('recording_url', models.URLField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_recording_sessions', to='landing.event')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recording_sessions', to='api.competitionfield')),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CategoryRefereeScoreEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('reveal', 'Reveal')], default='update', max_length=20)),
                ('source', models.CharField(choices=[('referee_app', 'Referee App'), ('competition_admin', 'Competition Admin'), ('system', 'System')], default='competition_admin', max_length=20)),
                ('score_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('previous_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('video_offset_ms', models.IntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('athlete_score', models.ForeignKey(help_text='The athlete/team score affected by this event', on_delete=django.db.models.deletion.CASCADE, related_name='score_events', to='api.categoryathletescore')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('referee', models.ForeignKey(help_text='The referee that produced this event', limit_choices_to={'is_referee': True}, on_delete=django.db.models.deletion.CASCADE, related_name='category_score_events', to='api.athlete')),
                ('recording_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_score_events', to='api.fieldrecordingsession')),
            ],
            options={
                'verbose_name': 'Category Referee Score Event',
                'verbose_name_plural': 'Category Referee Score Events',
                'ordering': ['timestamp', 'id'],
            },
        ),
        migrations.AddField(
            model_name='refereepointevent',
            name='recording_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referee_point_events', to='api.fieldrecordingsession'),
        ),
        migrations.AddIndex(
            model_name='fieldrecordingsession',
            index=models.Index(fields=['event', 'field', 'status'], name='api_fieldre_event_i_c15d5e_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldrecordingsession',
            index=models.Index(fields=['started_at'], name='api_fieldre_started_87574c_idx'),
        ),
        migrations.AddIndex(
            model_name='categoryrefereescoreevent',
            index=models.Index(fields=['athlete_score', 'timestamp'], name='api_categor_athlete_02fa50_idx'),
        ),
        migrations.AddIndex(
            model_name='categoryrefereescoreevent',
            index=models.Index(fields=['referee', 'timestamp'], name='api_categor_referee_8c162e_idx'),
        ),
    ]
