# Generated by Django 5.2.1 on 2025-11-09 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_add_referee_point_event_and_central_referee'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventParticipation',
            fields=[
            ],
            options={
                'verbose_name': 'Event participation',
                'verbose_name_plural': 'Event participations',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.trainingseminarparticipation',),
        ),
        migrations.AlterModelOptions(
            name='trainingseminarparticipation',
            options={'verbose_name': 'Event participation', 'verbose_name_plural': 'Event participations'},
        ),
        migrations.AlterField(
            model_name='match',
            name='central_referee',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_referee': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='central_for_matches', to='api.athlete'),
        ),
        migrations.AlterField(
            model_name='refereepointevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='refereepointevent',
            name='referee',
            field=models.ForeignKey(limit_choices_to={'is_referee': True}, on_delete=django.db.models.deletion.CASCADE, to='api.athlete'),
        ),
    ]
