# Generated by Django 5.2.12 on 2026-06-06 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_competition_trainingseminar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExternalAPIClient',
        ),
    ]
