# Generated by Django 5.2.12 on 2026-06-06 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_remove_externalapiclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradehistory',
            name='obtained_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
