# Generated by Django 5.2.1 on 2025-11-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_eventparticipation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refereepointevent',
            name='metadata',
            field=models.JSONField(blank=True, help_text="Optional JSON object for extra event data. Common keys: 'round' (int), 'central' (bool), 'reason' (string), 'origin' (string). Example: {'round': 2, 'central': true, 'reason': 'excessive contact'}", null=True),
        ),
    ]
