# Generated by Django 5.2.1 on 2025-11-13 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_refereepointevent_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submitted', 'Profile Submitted'), ('approved', 'Profile Approved'), ('rejected', 'Profile Rejected'), ('revision_requested', 'Revision Requested'), ('updated', 'Profile Updated'), ('resubmitted', 'Profile Resubmitted')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_log', to='api.athlete')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Athlete Activity',
                'verbose_name_plural': 'Athlete Activities',
                'ordering': ['-timestamp'],
            },
        ),
    ]
