# Generated by Django 5.2.1 on 2025-11-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_athlete_date_of_birth_and_category_competition'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='image',
            field=models.ImageField(blank=True, help_text='Grade badge image (SVG or PNG)', null=True, upload_to='grades/'),
        ),
    ]
