# Generated by Django 5.2.1 on 2025-11-21 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_add_grade_image'),
        ('landing', '0008_alter_newscomment_options_alter_newspost_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='winner',
        ),
        migrations.RemoveField(
            model_name='team',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.AddField(
            model_name='group',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='landing.event'),
        ),
        migrations.AlterField(
            model_name='club',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clubs', to='api.city'),
        ),
        migrations.AlterField(
            model_name='group',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='api.competition'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='visa',
            unique_together={('athlete', 'visa_type', 'issued_date')},
        ),
        migrations.AddIndex(
            model_name='athlete',
            index=models.Index(fields=['club', 'status'], name='api_athlete_club_id_7f309f_idx'),
        ),
        migrations.AddIndex(
            model_name='athlete',
            index=models.Index(fields=['current_grade'], name='api_athlete_current_a89674_idx'),
        ),
        migrations.AddIndex(
            model_name='athlete',
            index=models.Index(fields=['is_coach'], name='api_athlete_is_coac_708bf5_idx'),
        ),
        migrations.AddIndex(
            model_name='athlete',
            index=models.Index(fields=['is_referee'], name='api_athlete_is_refe_007646_idx'),
        ),
        migrations.AddIndex(
            model_name='athlete',
            index=models.Index(fields=['status', 'submitted_date'], name='api_athlete_status_d66a16_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['event', 'type'], name='api_categor_event_i_343b24_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['competition', 'type'], name='api_categor_competi_de1210_idx'),
        ),
        migrations.AddIndex(
            model_name='categoryathletescore',
            index=models.Index(fields=['category', 'status'], name='api_categor_categor_2b2894_idx'),
        ),
        migrations.AddIndex(
            model_name='categoryathletescore',
            index=models.Index(fields=['athlete', 'status'], name='api_categor_athlete_01b156_idx'),
        ),
        migrations.AddIndex(
            model_name='categoryathletescore',
            index=models.Index(fields=['submitted_date'], name='api_categor_submitt_79723d_idx'),
        ),
        migrations.AddIndex(
            model_name='categoryathletescore',
            index=models.Index(fields=['status', 'submitted_by_athlete'], name='api_categor_status_a48fcd_idx'),
        ),
        migrations.AddIndex(
            model_name='gradehistory',
            index=models.Index(fields=['athlete', 'status'], name='api_gradehi_athlete_c6e8ab_idx'),
        ),
        migrations.AddIndex(
            model_name='gradehistory',
            index=models.Index(fields=['obtained_date'], name='api_gradehi_obtaine_c3f085_idx'),
        ),
        migrations.AddIndex(
            model_name='gradehistory',
            index=models.Index(fields=['status', 'submitted_date'], name='api_gradehi_status_75fb45_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingseminarparticipation',
            index=models.Index(fields=['athlete', 'status'], name='api_trainin_athlete_21adfb_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingseminarparticipation',
            index=models.Index(fields=['status', 'submitted_date'], name='api_trainin_status_df32f7_idx'),
        ),
        migrations.AddIndex(
            model_name='visa',
            index=models.Index(fields=['athlete', 'visa_type', 'issued_date'], name='api_visa_athlete_4fcb59_idx'),
        ),
        migrations.AddIndex(
            model_name='visa',
            index=models.Index(fields=['athlete', 'visa_type', '-issued_date'], name='api_visa_athlete_c46c69_idx'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(condition=models.Q(('event__isnull', False)), fields=('event', 'name'), name='unique_group_per_event'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(condition=models.Q(('competition__isnull', False)), fields=('competition', 'name'), name='unique_group_per_competition'),
        ),
    ]
