# Generated by Django 5.2.1 on 2025-12-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_add_grade_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], help_text="Athlete's gender for category enrollment", max_length=10, null=True),
        ),
    ]
