# Generated by Django 5.2.1 on 2025-12-19 10:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_add_athlete_gender'),
        ('landing', '0008_alter_newscomment_options_alter_newspost_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='api.competition'),
        ),
        migrations.AlterField(
            model_name='category',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='landing.event'),
        ),
        migrations.AlterField(
            model_name='gradehistory',
            name='obtained_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddIndex(
            model_name='athlete',
            index=models.Index(fields=['status', '-submitted_date'], name='api_athlete_status_ee51c5_idx'),
        ),
        migrations.AddIndex(
            model_name='athlete',
            index=models.Index(fields=['club', 'status'], name='api_athlete_club_id_7f309f_idx'),
        ),
        migrations.AddIndex(
            model_name='athlete',
            index=models.Index(fields=['current_grade'], name='api_athlete_current_a89674_idx'),
        ),
        migrations.AddIndex(
            model_name='athlete',
            index=models.Index(fields=['is_coach'], name='api_athlete_is_coac_708bf5_idx'),
        ),
        migrations.AddIndex(
            model_name='athlete',
            index=models.Index(fields=['is_referee'], name='api_athlete_is_refe_007646_idx'),
        ),
        migrations.AddIndex(
            model_name='categoryathletescore',
            index=models.Index(fields=['category', 'status'], name='api_categor_categor_2b2894_idx'),
        ),
        migrations.AddIndex(
            model_name='categoryathletescore',
            index=models.Index(fields=['athlete', 'status'], name='api_categor_athlete_01b156_idx'),
        ),
        migrations.AddIndex(
            model_name='categoryathletescore',
            index=models.Index(fields=['status', '-submitted_date'], name='api_categor_status_c4af93_idx'),
        ),
        migrations.AddIndex(
            model_name='categoryathletescore',
            index=models.Index(fields=['type', 'status'], name='api_categor_type_91bcb1_idx'),
        ),
        migrations.AddIndex(
            model_name='gradehistory',
            index=models.Index(fields=['athlete', 'status'], name='api_gradehi_athlete_c6e8ab_idx'),
        ),
        migrations.AddIndex(
            model_name='gradehistory',
            index=models.Index(fields=['status', '-submitted_date'], name='api_gradehi_status_78d606_idx'),
        ),
        migrations.AddIndex(
            model_name='gradehistory',
            index=models.Index(fields=['athlete', '-obtained_date'], name='api_gradehi_athlete_ead8ce_idx'),
        ),
        migrations.AddConstraint(
            model_name='athlete',
            constraint=models.CheckConstraint(condition=models.Q(('expiration_date__gt', models.F('registered_date')), ('expiration_date__isnull', True), _connector='OR'), name='athlete_expiration_after_registration'),
        ),
        migrations.AddConstraint(
            model_name='competition',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date')), ('end_date__isnull', True), _connector='OR'), name='competition_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='visa',
            constraint=models.CheckConstraint(condition=models.Q(('visa_type', 'medical'), ('visa_type', 'annual'), _connector='OR'), name='visa_valid_type'),
        ),
    ]
