# Generated by Django 5.2.12 on 2026-06-06 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_category_competition_alter_category_event_and_more'),
        ('landing', '0012_event_sync_history_fields'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='athlete',
            name='athlete_expiration_after_registration',
        ),
        migrations.RemoveConstraint(
            model_name='visa',
            name='visa_valid_type',
        ),
        migrations.RemoveIndex(
            model_name='athlete',
            name='api_athlete_status_ee51c5_idx',
        ),
        migrations.RemoveIndex(
            model_name='categoryathletescore',
            name='api_categor_status_c4af93_idx',
        ),
        migrations.RemoveIndex(
            model_name='categoryathletescore',
            name='api_categor_type_91bcb1_idx',
        ),
        migrations.RemoveIndex(
            model_name='gradehistory',
            name='api_gradehi_status_78d606_idx',
        ),
        migrations.RemoveIndex(
            model_name='gradehistory',
            name='api_gradehi_athlete_ead8ce_idx',
        ),
        migrations.RemoveField(
            model_name='category',
            name='competition',
        ),
        migrations.AlterField(
            model_name='athlete',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='landing.event'),
        ),
        migrations.AlterField(
            model_name='gradehistory',
            name='obtained_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
