# Generated by Django 5.2.1 on 2025-11-23 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_cleanup_deprecated_models'),
        ('landing', '0008_alter_newscomment_options_alter_newspost_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryRefereeScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, help_text='Score given by this referee (typically 0-10 scale)', max_digits=5)),
                ('submitted_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes from referee', null=True)),
            ],
            options={
                'verbose_name': 'Category Referee Score',
                'verbose_name_plural': 'Category Referee Scores',
            },
        ),
        migrations.AddField(
            model_name='categoryrefereescore',
            name='athlete_score',
            field=models.ForeignKey(help_text='The athlete/team result being scored', on_delete=django.db.models.deletion.CASCADE, related_name='referee_scores', to='api.categoryathletescore'),
        ),
        migrations.AddField(
            model_name='categoryrefereescore',
            name='referee',
            field=models.ForeignKey(help_text='The referee providing this score', limit_choices_to={'is_referee': True}, on_delete=django.db.models.deletion.CASCADE, related_name='given_category_scores', to='api.athlete'),
        ),
        migrations.AddIndex(
            model_name='categoryrefereescore',
            index=models.Index(fields=['athlete_score', 'referee'], name='api_categor_athlete_0191ff_idx'),
        ),
        migrations.AddIndex(
            model_name='categoryrefereescore',
            index=models.Index(fields=['submitted_date'], name='api_categor_submitt_203629_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='categoryrefereescore',
            unique_together={('athlete_score', 'referee')},
        ),
    ]
