# Generated by Django 5.2.1 on 2025-11-23 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_categoryrefereescore_and_more'),
        ('landing', '0008_alter_newscomment_options_alter_newspost_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryRefereeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Category Referee Assignment',
                'verbose_name_plural': 'Category Referee Assignments',
            },
        ),
        migrations.AddField(
            model_name='categoryrefereeassignment',
            name='category',
            field=models.OneToOneField(help_text='The category these referees are assigned to', on_delete=django.db.models.deletion.CASCADE, related_name='referee_assignment', to='api.category'),
        ),
        migrations.AddField(
            model_name='categoryrefereeassignment',
            name='referee_1',
            field=models.ForeignKey(blank=True, help_text='Referee 1 (R1)', limit_choices_to={'is_referee': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referee_1_categories', to='api.athlete'),
        ),
        migrations.AddField(
            model_name='categoryrefereeassignment',
            name='referee_2',
            field=models.ForeignKey(blank=True, help_text='Referee 2 (R2)', limit_choices_to={'is_referee': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referee_2_categories', to='api.athlete'),
        ),
        migrations.AddField(
            model_name='categoryrefereeassignment',
            name='referee_3',
            field=models.ForeignKey(blank=True, help_text='Referee 3 (R3)', limit_choices_to={'is_referee': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referee_3_categories', to='api.athlete'),
        ),
        migrations.AddField(
            model_name='categoryrefereeassignment',
            name='referee_4',
            field=models.ForeignKey(blank=True, help_text='Referee 4 (R4)', limit_choices_to={'is_referee': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referee_4_categories', to='api.athlete'),
        ),
        migrations.AddField(
            model_name='categoryrefereeassignment',
            name='referee_5',
            field=models.ForeignKey(blank=True, help_text='Referee 5 (R5)', limit_choices_to={'is_referee': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referee_5_categories', to='api.athlete'),
        ),
    ]
