# Generated by Django 5.2.12 on 2026-06-06 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_grade_history_obtained_date_editable'),
        ('api', '0038_remove_athlete_athlete_expiration_after_registration_and_more'),
    ]

    operations = [
    ]
