# Generated by Django 5.2.1 on 2025-11-23 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_categoryrefereeassignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryathletescore',
            name='athlete',
            field=models.ForeignKey(blank=True, help_text='Athlete being scored (null for team scores)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_scores', to='api.athlete'),
        ),
    ]

