# Generated by Django 5.2.1 on 2026-01-04 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_allow_null_athlete_for_team_scores'),
        ('landing', '0008_alter_newscomment_options_alter_newspost_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchRefereeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MatchRefereeScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red_corner_score', models.DecimalField(decimal_places=2, default=0, help_text='Score for red corner fighter', max_digits=5)),
                ('blue_corner_score', models.DecimalField(decimal_places=2, default=0, help_text='Score for blue corner fighter', max_digits=5)),
                ('submitted_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes from referee', null=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='api_categor_competi_de1210_idx',
        ),
        migrations.AlterUniqueTogether(
            name='trainingseminarparticipation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='athletematch',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='athlete_matches', to='landing.event'),
        ),
        migrations.AddField(
            model_name='trainingseminarparticipation',
            name='seminar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_participations', to='landing.event'),
        ),
        migrations.AlterField(
            model_name='trainingseminarparticipation',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Event this athlete participated in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seminar_participations', to='landing.event'),
        ),
        migrations.AlterUniqueTogether(
            name='trainingseminarparticipation',
            unique_together={('athlete', 'event')},
        ),
        migrations.AddField(
            model_name='matchrefereeassignment',
            name='match',
            field=models.OneToOneField(help_text='The match these referees are assigned to', on_delete=django.db.models.deletion.CASCADE, related_name='referee_assignment', to='api.match'),
        ),
        migrations.AddField(
            model_name='matchrefereeassignment',
            name='referee_1',
            field=models.ForeignKey(blank=True, help_text='Referee position 1 (R1)', limit_choices_to={'is_referee': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_r1_assignments', to='api.athlete'),
        ),
        migrations.AddField(
            model_name='matchrefereeassignment',
            name='referee_2',
            field=models.ForeignKey(blank=True, help_text='Referee position 2 (R2)', limit_choices_to={'is_referee': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_r2_assignments', to='api.athlete'),
        ),
        migrations.AddField(
            model_name='matchrefereeassignment',
            name='referee_3',
            field=models.ForeignKey(blank=True, help_text='Referee position 3 (R3)', limit_choices_to={'is_referee': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_r3_assignments', to='api.athlete'),
        ),
        migrations.AddField(
            model_name='matchrefereeassignment',
            name='referee_4',
            field=models.ForeignKey(blank=True, help_text='Referee position 4 (R4)', limit_choices_to={'is_referee': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_r4_assignments', to='api.athlete'),
        ),
        migrations.AddField(
            model_name='matchrefereeassignment',
            name='referee_5',
            field=models.ForeignKey(blank=True, help_text='Referee position 5 (R5)', limit_choices_to={'is_referee': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_r5_assignments', to='api.athlete'),
        ),
        migrations.AddField(
            model_name='matchrefereescore',
            name='match',
            field=models.ForeignKey(help_text='The match being scored', on_delete=django.db.models.deletion.CASCADE, related_name='simplified_referee_scores', to='api.match'),
        ),
        migrations.AddField(
            model_name='matchrefereescore',
            name='referee',
            field=models.ForeignKey(help_text='The referee providing this score', limit_choices_to={'is_referee': True}, on_delete=django.db.models.deletion.CASCADE, related_name='given_match_scores', to='api.athlete'),
        ),
        migrations.AddIndex(
            model_name='matchrefereescore',
            index=models.Index(fields=['match', 'referee'], name='api_matchre_match_i_808162_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='matchrefereescore',
            unique_together={('match', 'referee')},
        ),
    ]
