# Generated by Django 6.1 on 2026-08-31 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_fightgroupenrollment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fightgroupenrollment',
            new_name='api_fightgr_event_i_be2387_idx',
            old_name='api_fightgr_event_i_eb4365_idx',
        ),
        migrations.RenameIndex(
            model_name='fightgroupenrollment',
            new_name='api_fightgr_athlete_953bce_idx',
            old_name='api_fightgr_athlete_8e4255_idx',
        ),
    ]
