# Generated by Django 5.2.1 on 2026-01-04 20:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_matchrefereeassignment_matchrefereescore_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='athlete',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='athlete',
            name='created_offline',
            field=models.BooleanField(default=False, help_text='Whether this record was created offline'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='athlete',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='athlete',
            name='is_synced',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this record has been synced to all clients'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='Last time this record was synced to offline clients', null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='athlete',
            name='sync_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Hash of critical fields for quick change detection', max_length=64),
        ),
        migrations.AddField(
            model_name='athlete',
            name='temp_id',
            field=models.CharField(blank=True, db_index=True, help_text='Temporary ID from offline client before server assignment', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='version',
            field=models.IntegerField(default=1, help_text='Incremented on each update for conflict detection'),
        ),
    ]
