# Generated by Django 5.2.1 on 2026-02-04 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_athlete_created_at_athlete_created_by_and_more'),
        ('landing', '0008_alter_newscomment_options_alter_newspost_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='third_place',
        ),
        migrations.RemoveField(
            model_name='category',
            name='second_place',
        ),
        migrations.RemoveField(
            model_name='category',
            name='first_place',
        ),
        migrations.RemoveField(
            model_name='category',
            name='third_place_team',
        ),
        migrations.RemoveField(
            model_name='category',
            name='first_place_team',
        ),
        migrations.RemoveField(
            model_name='category',
            name='second_place_team',
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='api_categor_event_i_343b24_idx',
        ),
        migrations.RemoveField(
            model_name='category',
            name='type',
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['event'], name='api_categor_event_i_67e574_idx'),
        ),
        migrations.CreateModel(
            name='FightCategory',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.category')),
                ('first_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fight_first_place_categories', to='api.athlete')),
                ('second_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fight_second_place_categories', to='api.athlete')),
                ('third_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fight_third_place_categories', to='api.athlete')),
            ],
            options={
                'verbose_name': 'Fight Category',
                'verbose_name_plural': 'Fight Categories',
            },
            bases=('api.category',),
        ),
        migrations.CreateModel(
            name='SoloCategory',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.category')),
                ('first_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solo_first_place_categories', to='api.athlete')),
                ('second_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solo_second_place_categories', to='api.athlete')),
                ('third_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solo_third_place_categories', to='api.athlete')),
            ],
            options={
                'verbose_name': 'Solo Category',
                'verbose_name_plural': 'Solo Categories',
            },
            bases=('api.category',),
        ),
        migrations.CreateModel(
            name='TeamCategory',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.category')),
                ('first_place_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_place_team_categories', to='api.team')),
                ('second_place_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_place_team_categories', to='api.team')),
                ('third_place_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_place_team_categories', to='api.team')),
            ],
            options={
                'verbose_name': 'Team Category',
                'verbose_name_plural': 'Team Categories',
            },
            bases=('api.category',),
        ),
    ]
