# Generated by Django 5.1.6 on 2026-09-05 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_unaccent_extension'),
        ('landing', '0012_event_sync_history_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fightgroupenrollment',
            new_name='api_fightgr_event_i_eb4365_idx',
            old_name='api_fightgr_event_i_be2387_idx',
        ),
        migrations.RenameIndex(
            model_name='fightgroupenrollment',
            new_name='api_fightgr_athlete_8e4255_idx',
            old_name='api_fightgr_athlete_953bce_idx',
        ),
        migrations.AddField(
            model_name='notification',
            name='related_competition',
            field=models.ForeignKey(blank=True, help_text='Optional link to the competition/event this notification is about', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='landing.event'),
        ),
    ]
