# Generated by Django 5.2.1 on 2026-02-04 20:04

from django.db import migrations


def populate_category_types(apps, schema_editor):
    """
    Move existing Category objects to appropriate child model (SoloCategory, TeamCategory, FightCategory)
    Based on what type they would have had in the old schema.
    Default to SoloCategory if no clear indication.
    """
    Category = apps.get_model('api', 'Category')
    SoloCategory = apps.get_model('api', 'SoloCategory')
    TeamCategory = apps.get_model('api', 'TeamCategory')
    FightCategory = apps.get_model('api', 'FightCategory')
    
    for category in Category.objects.all():
        # Determine the type based on relationships and awards
        has_team_awards = hasattr(category, 'first_place_team') and (
            category.first_place_team_id or category.second_place_team_id or category.third_place_team_id
        )
        has_enrollments = category.teams.exists()
        
        # Create appropriate child instance
        if has_team_awards or has_enrollments:
            # This is a team category
            TeamCategory.objects.get_or_create(
                category_ptr=category,
                defaults={
                    'name': category.name,
                    'event': category.event,
                    'gender': category.gender,
                    'group': category.group,
                    'first_place_team_id': category.first_place_team_id if hasattr(category, 'first_place_team_id') else None,
                    'second_place_team_id': category.second_place_team_id if hasattr(category, 'second_place_team_id') else None,
                    'third_place_team_id': category.third_place_team_id if hasattr(category, 'third_place_team_id') else None,
                }
            )
        else:
            # Check if it's a fight category by checking for matches
            Match = apps.get_model('api', 'Match')
            if Match.objects.filter(category=category).exists():
                FightCategory.objects.get_or_create(
                    category_ptr=category,
                    defaults={
                        'name': category.name,
                        'event': category.event,
                        'gender': category.gender,
                        'group': category.group,
                        'first_place_id': category.first_place_id if hasattr(category, 'first_place_id') else None,
                        'second_place_id': category.second_place_id if hasattr(category, 'second_place_id') else None,
                        'third_place_id': category.third_place_id if hasattr(category, 'third_place_id') else None,
                    }
                )
            else:
                # Default to solo category
                SoloCategory.objects.get_or_create(
                    category_ptr=category,
                    defaults={
                        'name': category.name,
                        'event': category.event,
                        'gender': category.gender,
                        'group': category.group,
                        'first_place_id': category.first_place_id if hasattr(category, 'first_place_id') else None,
                        'second_place_id': category.second_place_id if hasattr(category, 'second_place_id') else None,
                        'third_place_id': category.third_place_id if hasattr(category, 'third_place_id') else None,
                    }
                )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_remove_category_third_place_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_category_types),
    ]
