# Generated by Django 5.1.6 on 2026-09-05 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_notification_related_competition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visa',
            name='visa_status',
        ),
    ]
