# Generated by Django 5.2.1 on 2026-02-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_populate_category_types'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['event', '-birth_year_end', 'name']},
        ),
        migrations.AddField(
            model_name='group',
            name='birth_year_end',
            field=models.IntegerField(blank=True, help_text='Ending birth year for this age group (e.g., 2018)', null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='birth_year_start',
            field=models.IntegerField(blank=True, help_text='Starting birth year for this age group (e.g., 2015)', null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(help_text="Group name (e.g., 'U12 Beginners', 'Youth 2015-2018')", max_length=100),
        ),
    ]
