# Generated by Django 5.1.6 on 2026-09-05 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_visa_status_computed_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='supporterathleterelation',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_supporter_relations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supporterathleterelation',
            name='reviewed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supporterathleterelation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Relationship must be approved by the athlete or an admin before it grants any permission.', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('result_submitted', 'Result Submitted'), ('result_approved', 'Result Approved'), ('result_rejected', 'Result Rejected'), ('result_revision_required', 'Result Revision Required'), ('grade_submitted', 'Grade Exam Submitted'), ('grade_approved', 'Grade Exam Approved'), ('grade_rejected', 'Grade Exam Rejected'), ('grade_revision_required', 'Grade Exam Revision Required'), ('seminar_submitted', 'Seminar Participation Submitted'), ('seminar_approved', 'Seminar Participation Approved'), ('seminar_rejected', 'Seminar Participation Rejected'), ('seminar_revision_required', 'Seminar Participation Revision Required'), ('competition_created', 'Competition Created'), ('competition_updated', 'Competition Updated'), ('system_announcement', 'System Announcement'), ('supporter_request', 'Supporter Relation Request'), ('supporter_approved', 'Supporter Relation Approved'), ('supporter_rejected', 'Supporter Relation Rejected')], max_length=30),
        ),
    ]
