# Generated by Django 5.2.1 on 2026-02-04 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_fix_group_competition_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryVideoRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(blank=True, help_text='Uploaded video file (MP4, WebM, etc.)', null=True, upload_to='category_videos/%Y/%m/%d/')),
                ('video_url', models.URLField(blank=True, help_text='External video URL (YouTube, Vimeo, streaming service)', max_length=500, null=True)),
                ('title', models.CharField(blank=True, help_text='Video title/description', max_length=200)),
                ('duration_seconds', models.IntegerField(blank=True, help_text='Total video duration in seconds', null=True)),
                ('recorded_at', models.DateTimeField(blank=True, help_text='When the video was recorded', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='When video was uploaded to system')),
                ('is_public', models.BooleanField(default=False, help_text='Whether video is publicly accessible')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the video')),
                ('category', models.ForeignKey(help_text='The category this video records (Solo or Team)', on_delete=django.db.models.deletion.CASCADE, related_name='video_recordings', to='api.category')),
            ],
            options={
                'verbose_name': 'Category Video Recording',
                'verbose_name_plural': 'Category Video Recordings',
                'ordering': ['-recorded_at', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CategoryVideoSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(blank=True, help_text='Team name for this segment (for Team categories)', max_length=200)),
                ('start_time_seconds', models.IntegerField(help_text='Start of segment in seconds (0-based)')),
                ('end_time_seconds', models.IntegerField(blank=True, help_text='End of segment in seconds (optional)', null=True)),
                ('label', models.CharField(blank=True, help_text='e.g., "John Doe - Song Than", "Team A Performance"', max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Specific events/notes during this segment')),
                ('athlete', models.ForeignKey(blank=True, help_text='Athlete performing in this segment (for Solo categories)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_segments', to='api.athlete')),
                ('video_recording', models.ForeignKey(help_text='The video this segment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='api.categoryvideorecording')),
            ],
            options={
                'verbose_name': 'Video Segment',
                'verbose_name_plural': 'Video Segments',
                'ordering': ['start_time_seconds'],
            },
        ),
        migrations.CreateModel(
            name='MatchVideoRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(blank=True, help_text='Uploaded video file (MP4, WebM, etc.)', null=True, upload_to='match_videos/%Y/%m/%d/')),
                ('video_url', models.URLField(blank=True, help_text='External video URL (YouTube, Vimeo, streaming service)', max_length=500, null=True)),
                ('title', models.CharField(blank=True, help_text='Video title/description', max_length=200)),
                ('duration_seconds', models.IntegerField(blank=True, help_text='Total video duration in seconds', null=True)),
                ('recorded_at', models.DateTimeField(blank=True, help_text='When the video was recorded', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='When video was uploaded to system')),
                ('is_public', models.BooleanField(default=False, help_text='Whether video is publicly accessible')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the video')),
                ('match', models.ForeignKey(help_text='The match this video records', on_delete=django.db.models.deletion.CASCADE, related_name='video_recordings', to='api.match')),
            ],
            options={
                'verbose_name': 'Match Video Recording',
                'verbose_name_plural': 'Match Video Recordings',
                'ordering': ['-recorded_at', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchVideoSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(help_text='Round number (1, 2, 3, etc.)')),
                ('start_time_seconds', models.IntegerField(help_text='Start of segment in seconds (0-based)')),
                ('end_time_seconds', models.IntegerField(blank=True, help_text='End of segment in seconds (optional)', null=True)),
                ('label', models.CharField(blank=True, help_text='e.g., "Round 2 - Red Corner Attack"', max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Specific events/notes during this segment')),
                ('video_recording', models.ForeignKey(help_text='The video this segment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='api.matchvideorecording')),
            ],
            options={
                'verbose_name': 'Match Video Segment',
                'verbose_name_plural': 'Match Video Segments',
                'ordering': ['round_number', 'start_time_seconds'],
            },
        ),
        migrations.CreateModel(
            name='RefereePointEventTimestamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_seconds', models.IntegerField(help_text='When in the video this event occurred (seconds)')),
                ('description', models.CharField(blank=True, help_text='e.g., "Kick to head", "Takedown", "Penalty for contact"', max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Additional context about this event')),
                ('point_event', models.OneToOneField(help_text='The scoring event', on_delete=django.db.models.deletion.CASCADE, related_name='video_timestamp', to='api.refereepointevent')),
                ('video_recording', models.ForeignKey(help_text='The video containing this event', on_delete=django.db.models.deletion.CASCADE, related_name='timestamped_events', to='api.matchvideorecording')),
            ],
            options={
                'verbose_name': 'Point Event Timestamp',
                'verbose_name_plural': 'Point Event Timestamps',
                'ordering': ['timestamp_seconds'],
            },
        ),
    ]
