# Generated by Django 5.2.1 on 2026-02-04 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_add_video_recording_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_number',
            field=models.CharField(blank=True, help_text='Unique identifier for this category (e.g., C1, C2, SOLO-M-1)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='match_number',
            field=models.CharField(blank=True, help_text='Unique identifier for this match (e.g., M1, M2, F-C1-Q1)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20),
        ),
    ]
