# Generated by Django 6.1 on 2026-09-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_alter_athlete_options_alter_athletematch_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('result_submitted', 'Rezultat trimis'), ('result_approved', 'Rezultat aprobat'), ('result_rejected', 'Rezultat respins'), ('result_revision_required', 'Rezultat cu revizie solicitată'), ('grade_submitted', 'Examen de grad trimis'), ('grade_approved', 'Examen de grad aprobat'), ('grade_rejected', 'Examen de grad respins'), ('grade_revision_required', 'Examen de grad cu revizie solicitată'), ('seminar_submitted', 'Participare la seminar trimisă'), ('seminar_approved', 'Participare la seminar aprobată'), ('seminar_rejected', 'Participare la seminar respinsă'), ('seminar_revision_required', 'Participare la seminar cu revizie solicitată'), ('competition_created', 'Competiție creată'), ('competition_updated', 'Competiție actualizată'), ('system_announcement', 'Anunț de sistem'), ('supporter_request', 'Cerere relație susținător'), ('supporter_approved', 'Relație susținător aprobată'), ('supporter_rejected', 'Relație susținător respinsă'), ('profile_image_submitted', 'Poză de profil trimisă spre aprobare'), ('profile_image_approved', 'Poză de profil aprobată'), ('profile_image_rejected', 'Poză de profil respinsă')], max_length=30, verbose_name='Tip notificare'),
        ),
    ]
