# Generated by Django 5.2.1 on 2026-02-04 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_populate_numbers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryscoreactivity',
            name='performed_by',
        ),
        migrations.RemoveField(
            model_name='categoryscoreactivity',
            name='score',
        ),
        migrations.DeleteModel(
            name='AthleteActivity',
        ),
        migrations.DeleteModel(
            name='CategoryScoreActivity',
        ),
    ]
