# Generated by Django 5.2.1 on 2026-02-05 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_remove_activity_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='FightAthleteWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_weight_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Weight submitted ~1 week before competition (kg)', max_digits=5, null=True)),
                ('current_weight_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Weight measured on morning of competition (kg)', max_digits=5, null=True)),
                ('weight_loss_percentage', models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Calculated percentage weight loss', max_digits=5, null=True)),
                ('is_disqualified', models.BooleanField(default=False, help_text='Mark as disqualified if weight difference exceeds limits')),
                ('disqualification_reason', models.CharField(blank=True, help_text='Reason for disqualification (e.g., "Excessive weight loss")', max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about weight-in')),
                ('recorded_at', models.DateTimeField(auto_now=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fight_weights', to='api.athlete')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_weights', to='api.fightcategory')),
            ],
            options={
                'verbose_name': 'Fight Athlete Weight',
                'verbose_name_plural': 'Fight Athlete Weights',
                'unique_together': {('category', 'athlete')},
            },
        ),
    ]
