# Generated by Django 6.1 on 2026-09-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='european_medals_bronze',
            field=models.PositiveIntegerField(default=0, verbose_name='Medalii bronz - European'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='european_medals_gold',
            field=models.PositiveIntegerField(default=0, verbose_name='Medalii aur - European'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='european_medals_silver',
            field=models.PositiveIntegerField(default=0, verbose_name='Medalii argint - European'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='world_medals_bronze',
            field=models.PositiveIntegerField(default=0, verbose_name='Medalii bronz - Mondial'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='world_medals_gold',
            field=models.PositiveIntegerField(default=0, verbose_name='Medalii aur - Mondial'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='world_medals_silver',
            field=models.PositiveIntegerField(default=0, verbose_name='Medalii argint - Mondial'),
        ),
    ]
