# Generated by Django 5.2.1 on 2026-02-05 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_add_fight_athlete_weights'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fightathleteweight',
            name='notes',
        ),
        migrations.AlterField(
            model_name='fightathleteweight',
            name='current_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight on morning of competition (kg)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='fightathleteweight',
            name='disqualification_reason',
            field=models.CharField(blank=True, help_text='Reason for disqualification', max_length=255),
        ),
        migrations.AlterField(
            model_name='fightathleteweight',
            name='is_disqualified',
            field=models.BooleanField(default=False, help_text='Mark as disqualified if weight exceeds limits'),
        ),
        migrations.AlterField(
            model_name='fightathleteweight',
            name='pre_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight submitted ~1 week before (kg)', max_digits=5, null=True),
        ),
    ]
