# Generated by Django 6.1 on 2026-09-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_add_athlete_international_medals'),
    ]

    operations = [
        migrations.AddField(
            model_name='visa',
            name='submitted_by_athlete',
            field=models.BooleanField(default=False, help_text='Bifat dacă a fost trimis chiar de sportiv.', verbose_name='Trimis de sportiv'),
        ),
    ]
