# Generated by Django 5.2.1 on 2026-02-05 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_remove_fight_weight_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryathlete',
            name='place',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1st Place'), (2, '2nd Place'), (3, '3rd Place')], help_text='Award placement', null=True),
        ),
        migrations.AddField(
            model_name='categoryteam',
            name='place',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1st Place'), (2, '2nd Place'), (3, '3rd Place')], help_text='Award placement', null=True),
        ),
        migrations.AddField(
            model_name='fightathleteweight',
            name='place',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1st Place'), (2, '2nd Place'), (3, '3rd Place')], help_text='Award placement', null=True),
        ),
        migrations.AlterField(
            model_name='fightathleteweight',
            name='current_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight measured on competition day', max_digits=5, null=True, verbose_name='Match Day Weight (kg)'),
        ),
        migrations.AlterField(
            model_name='fightathleteweight',
            name='pre_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight submitted ~1 week before competition', max_digits=5, null=True, verbose_name='Registered Weight (kg)'),
        ),
    ]
