# Generated by Django 5.2.1 on 2026-02-05 00:55

from django.db import migrations


def create_matchrefereeassignment_table(apps, schema_editor):
    """Manually create the MatchRefereeAssignment table that was missing from migration 0041"""
    schema_editor.execute("""
        CREATE TABLE IF NOT EXISTS "api_matchrefereeassignment" (
            "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
            "match_id" bigint NOT NULL UNIQUE REFERENCES "api_match" ("id") DEFERRABLE INITIALLY DEFERRED,
            "referee_1_id" bigint NULL REFERENCES "api_athlete" ("id") DEFERRABLE INITIALLY DEFERRED,
            "referee_2_id" bigint NULL REFERENCES "api_athlete" ("id") DEFERRABLE INITIALLY DEFERRED,
            "referee_3_id" bigint NULL REFERENCES "api_athlete" ("id") DEFERRABLE INITIALLY DEFERRED,
            "referee_4_id" bigint NULL REFERENCES "api_athlete" ("id") DEFERRABLE INITIALLY DEFERRED,
            "referee_5_id" bigint NULL REFERENCES "api_athlete" ("id") DEFERRABLE INITIALLY DEFERRED
        );
    """)
    
    # Create indexes for foreign keys
    schema_editor.execute('CREATE INDEX IF NOT EXISTS "api_matchrefereeassignment_match_id" ON "api_matchrefereeassignment" ("match_id");')
    schema_editor.execute('CREATE INDEX IF NOT EXISTS "api_matchrefereeassignment_referee_1_id" ON "api_matchrefereeassignment" ("referee_1_id");')
    schema_editor.execute('CREATE INDEX IF NOT EXISTS "api_matchrefereeassignment_referee_2_id" ON "api_matchrefereeassignment" ("referee_2_id");')
    schema_editor.execute('CREATE INDEX IF NOT EXISTS "api_matchrefereeassignment_referee_3_id" ON "api_matchrefereeassignment" ("referee_3_id");')
    schema_editor.execute('CREATE INDEX IF NOT EXISTS "api_matchrefereeassignment_referee_4_id" ON "api_matchrefereeassignment" ("referee_4_id");')
    schema_editor.execute('CREATE INDEX IF NOT EXISTS "api_matchrefereeassignment_referee_5_id" ON "api_matchrefereeassignment" ("referee_5_id");')


def drop_matchrefereeassignment_table(apps, schema_editor):
    """Drop the table on migration reversal"""
    schema_editor.execute('DROP TABLE IF EXISTS "api_matchrefereeassignment";')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_add_place_to_enrollments'),
    ]

    operations = [
        migrations.RunPython(create_matchrefereeassignment_table, drop_matchrefereeassignment_table),
    ]
