# Generated by Django 6.1 on 2026-09-11 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_notification_visa_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsettings',
            name='email_on_grade_status_change',
            field=models.BooleanField(default=True, verbose_name='Email la schimbarea stării gradului'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='email_on_seminar_status_change',
            field=models.BooleanField(default=True, verbose_name='Email la schimbarea stării participării la seminar'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='email_on_visa_status_change',
            field=models.BooleanField(default=True, verbose_name='Email la schimbarea stării vizei'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='notify_via_whatsapp',
            field=models.BooleanField(default=False, verbose_name='Notifică prin WhatsApp'),
        ),
    ]
