# Generated by Django 5.2.1 on 2026-02-05 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_fix_matchrefereeassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryathlete',
            name='ref1_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Referee 1 score', max_digits=5, null=True, verbose_name='REF1'),
        ),
        migrations.AddField(
            model_name='categoryathlete',
            name='ref2_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Referee 2 score', max_digits=5, null=True, verbose_name='REF2'),
        ),
        migrations.AddField(
            model_name='categoryathlete',
            name='ref3_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Referee 3 score', max_digits=5, null=True, verbose_name='REF3'),
        ),
        migrations.AddField(
            model_name='categoryathlete',
            name='ref4_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Referee 4 score', max_digits=5, null=True, verbose_name='REF4'),
        ),
        migrations.AddField(
            model_name='categoryathlete',
            name='ref5_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Referee 5 score', max_digits=5, null=True, verbose_name='REF5'),
        ),
        migrations.AddField(
            model_name='categoryteam',
            name='ref1_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Referee 1 score', max_digits=5, null=True, verbose_name='REF1'),
        ),
        migrations.AddField(
            model_name='categoryteam',
            name='ref2_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Referee 2 score', max_digits=5, null=True, verbose_name='REF2'),
        ),
        migrations.AddField(
            model_name='categoryteam',
            name='ref3_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Referee 3 score', max_digits=5, null=True, verbose_name='REF3'),
        ),
        migrations.AddField(
            model_name='categoryteam',
            name='ref4_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Referee 4 score', max_digits=5, null=True, verbose_name='REF4'),
        ),
        migrations.AddField(
            model_name='categoryteam',
            name='ref5_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Referee 5 score', max_digits=5, null=True, verbose_name='REF5'),
        ),
    ]
