# Generated by Django 5.2.1 on 2026-02-05 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_add_referee_scores_to_enrollments'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryathlete',
            name='disqualified',
            field=models.BooleanField(default=False, help_text='Mark as disqualified'),
        ),
        migrations.AddField(
            model_name='categoryteam',
            name='disqualified',
            field=models.BooleanField(default=False, help_text='Mark as disqualified'),
        ),
        migrations.AlterField(
            model_name='categoryathlete',
            name='place',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1st Place'), (2, '2nd Place'), (3, '3rd Place')], help_text='Award placement (auto-calculated from total score)', null=True),
        ),
        migrations.AlterField(
            model_name='categoryteam',
            name='place',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1st Place'), (2, '2nd Place'), (3, '3rd Place')], help_text='Award placement (auto-calculated from total score)', null=True),
        ),
    ]
