# Generated by Django 6.1.1 on 2026-09-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='license_image',
            field=models.ImageField(blank=True, null=True, upload_to='license_images/', verbose_name='Poză legitimație'),
        ),
    ]
