# Generated by Django 5.2.1 on 2026-02-05 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_add_disqualified_to_enrollments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchrefereeassignment',
            name='referee_1',
            field=models.ForeignKey(blank=True, help_text='Referee position 1 (R1)', limit_choices_to={'is_referee': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_r1_assignments', to='api.athlete', verbose_name='Referee 1'),
        ),
        migrations.AlterField(
            model_name='matchrefereeassignment',
            name='referee_2',
            field=models.ForeignKey(blank=True, help_text='Referee position 2 (R2)', limit_choices_to={'is_referee': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_r2_assignments', to='api.athlete', verbose_name='Referee 2'),
        ),
        migrations.AlterField(
            model_name='matchrefereeassignment',
            name='referee_3',
            field=models.ForeignKey(blank=True, help_text='Referee position 3 (R3)', limit_choices_to={'is_referee': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_r3_assignments', to='api.athlete', verbose_name='Referee 3'),
        ),
        migrations.AlterField(
            model_name='matchrefereeassignment',
            name='referee_4',
            field=models.ForeignKey(blank=True, help_text='Referee position 4 (R4)', limit_choices_to={'is_referee': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_r4_assignments', to='api.athlete', verbose_name='Referee 4'),
        ),
        migrations.AlterField(
            model_name='matchrefereeassignment',
            name='referee_5',
            field=models.ForeignKey(blank=True, help_text='Referee position 5 (R5)', limit_choices_to={'is_referee': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_r5_assignments', to='api.athlete', verbose_name='Referee 5'),
        ),
        migrations.AlterField(
            model_name='refereescore',
            name='referee',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_referee': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.athlete'),
        ),
    ]
