# Generated by Django 6.1.1 on 2026-09-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_athlete_license_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='is_licensed',
            field=models.BooleanField(default=True, verbose_name='Sportiv legitimat'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='license_request_document',
            field=models.FileField(blank=True, null=True, upload_to='license_requests/', verbose_name='Cerere de legitimare'),
        ),
    ]
