# Generated by Django 5.2.1 on 2026-02-05 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_allow_null_referee_in_refereescore'),
    ]

    operations = [
        migrations.CreateModel(
            name='AthletePerformanceVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(blank=True, help_text='Uploaded video file (MP4, WebM, etc.)', null=True, upload_to='athlete_videos/%Y/%m/%d/')),
                ('video_url', models.URLField(blank=True, help_text='External video URL (YouTube, Vimeo, streaming service)', max_length=500, null=True)),
                ('title', models.CharField(blank=True, help_text='Video title/description', max_length=200)),
                ('duration_seconds', models.IntegerField(blank=True, help_text='Total video duration in seconds', null=True)),
                ('recorded_at', models.DateTimeField(blank=True, help_text='When the video was recorded', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='When video was uploaded to system')),
                ('is_public', models.BooleanField(default=False, help_text='Whether video is publicly accessible')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the video')),
                ('athlete_score', models.OneToOneField(help_text='The athlete score entry this video documents', on_delete=django.db.models.deletion.CASCADE, related_name='performance_video', to='api.categoryathletescore')),
            ],
            options={
                'verbose_name': 'Athlete Performance Video',
                'verbose_name_plural': 'Athlete Performance Videos',
                'ordering': ['-recorded_at', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamPerformanceVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(blank=True, help_text='Uploaded video file (MP4, WebM, etc.)', null=True, upload_to='team_videos/%Y/%m/%d/')),
                ('video_url', models.URLField(blank=True, help_text='External video URL (YouTube, Vimeo, streaming service)', max_length=500, null=True)),
                ('title', models.CharField(blank=True, help_text='Video title/description', max_length=200)),
                ('duration_seconds', models.IntegerField(blank=True, help_text='Total video duration in seconds', null=True)),
                ('recorded_at', models.DateTimeField(blank=True, help_text='When the video was recorded', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='When video was uploaded to system')),
                ('is_public', models.BooleanField(default=False, help_text='Whether video is publicly accessible')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the video')),
                ('category_team', models.OneToOneField(help_text='The team enrollment this video documents', on_delete=django.db.models.deletion.CASCADE, related_name='performance_video', to='api.categoryteam')),
            ],
            options={
                'verbose_name': 'Team Performance Video',
                'verbose_name_plural': 'Team Performance Videos',
                'ordering': ['-recorded_at', '-uploaded_at'],
            },
        ),
    ]
