# Generated by Django 6.1.1 on 2026-09-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_athlete_is_licensed_athlete_license_request_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data acceptării termenilor'),
        ),
    ]
