# Generated by Django 6.1.1 on 2026-09-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_user_terms_accepted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='nationality',
            field=models.CharField(blank=True, default='Română', max_length=100, null=True, verbose_name='Naționalitate'),
        ),
    ]
