# Generated by Django 6.1.1 on 2026-09-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_athlete_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Număr legitimație'),
        ),
    ]
