# Generated by Django 6.1 on 2026-09-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='referee_category',
            field=models.CharField(blank=True, choices=[('A', 'Categoria A'), ('B', 'Categoria B'), ('C', 'Categoria C'), ('stagiar', 'Stagiar')], help_text='Doar pentru arbitri naționali (Categoria A/B/C sau Stagiar).', max_length=20, null=True, verbose_name='Categorie arbitru'),
        ),
    ]
