# Generated by Django 6.1 on 2026-09-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='youtube_url',
            field=models.URLField(blank=True, null=True, verbose_name='YouTube'),
        ),
    ]
