# Generated by Django 5.2.1 on 2026-02-06 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_seed_default_titles_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refereepointeventtimestamp',
            name='point_event',
        ),
        migrations.RemoveField(
            model_name='refereepointeventtimestamp',
            name='video_recording',
        ),
        migrations.DeleteModel(
            name='MatchVideoSegment',
        ),
        migrations.DeleteModel(
            name='RefereePointEventTimestamp',
        ),
    ]
