# Generated by Django 6.1 on 2026-09-18 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_club_youtube_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('result_submitted', 'Rezultat trimis'), ('result_approved', 'Rezultat aprobat'), ('result_rejected', 'Rezultat respins'), ('result_revision_required', 'Rezultat cu revizie solicitată'), ('grade_submitted', 'Examen de grad trimis'), ('grade_approved', 'Examen de grad aprobat'), ('grade_rejected', 'Examen de grad respins'), ('grade_revision_required', 'Examen de grad cu revizie solicitată'), ('seminar_submitted', 'Participare la seminar trimisă'), ('seminar_approved', 'Participare la seminar aprobată'), ('seminar_rejected', 'Participare la seminar respinsă'), ('seminar_revision_required', 'Participare la seminar cu revizie solicitată'), ('visa_submitted', 'Viză trimisă'), ('visa_approved', 'Viză aprobată'), ('visa_rejected', 'Viză respinsă'), ('visa_revision_required', 'Viză cu revizie solicitată'), ('competition_created', 'Competiție creată'), ('competition_updated', 'Competiție actualizată'), ('system_announcement', 'Anunț de sistem'), ('supporter_request', 'Cerere relație susținător'), ('supporter_approved', 'Relație susținător aprobată'), ('supporter_rejected', 'Relație susținător respinsă'), ('profile_image_submitted', 'Poză de profil trimisă spre aprobare'), ('profile_image_approved', 'Poză de profil aprobată'), ('profile_image_rejected', 'Poză de profil respinsă'), ('account_approved', 'Cont aprobat'), ('account_rejected', 'Cont respins'), ('profile_update_approved', 'Actualizare profil aprobată'), ('athlete_registered', 'Sportiv nou înregistrat')], max_length=30, verbose_name='Tip notificare'),
        ),
        migrations.CreateModel(
            name='AssistantConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data creării')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data actualizării')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Utilizator')),
            ],
            options={
                'verbose_name': 'Conversație asistent',
                'verbose_name_plural': 'Conversații asistent',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AssistantMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Utilizator'), ('assistant', 'Asistent')], max_length=10, verbose_name='Rol')),
                ('content', models.TextField(blank=True, verbose_name='Conținut')),
                ('tool_calls', models.JSONField(blank=True, default=list, verbose_name='Apeluri unelte')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data creării')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.assistantconversation', verbose_name='Conversație')),
            ],
            options={
                'verbose_name': 'Mesaj asistent',
                'verbose_name_plural': 'Mesaje asistent',
                'ordering': ['created_at'],
            },
        ),
    ]
