# Generated by Django 6.1 on 2026-09-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fightathleteweight',
            name='is_weight_locked',
            field=models.BooleanField(default=False, help_text='Blocată automat după confirmarea greutății la cântar, pentru a preveni modificări accidentale. Poate fi deblocată manual pentru o corecție.', verbose_name='Greutate blocată'),
        ),
    ]
