# Generated by Django 6.1 on 2026-09-20 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_add_fight_athlete_weight_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionreferee',
            name='county',
            field=models.CharField(blank=True, default='', help_text='Județul arbitrului, afișat pe delegarea oficială.', max_length=50, verbose_name='Județ'),
        ),
        migrations.AddField(
            model_name='competitionreferee',
            name='license_number',
            field=models.CharField(blank=True, default='', help_text='Numărul licenței de arbitru, afișat pe delegarea oficială.', max_length=50, verbose_name='Licență'),
        ),
        migrations.AddField(
            model_name='competitionreferee',
            name='role',
            field=models.CharField(blank=True, choices=[('central', 'Arbitru central'), ('corner', 'Arbitru de colț'), ('table', 'Arbitru masă centrală'), ('secretariat', 'Secretariat')], default='', help_text='Rolul cu care este delegat arbitrul la această competiție (folosit pe delegarea oficială).', max_length=20, verbose_name='Rol delegat'),
        ),
    ]
