# Generated by Django 6.1 on 2026-09-20 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_add_competition_referee_role_license_county'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitionreferee',
            name='county',
        ),
    ]
