# Generated by Django 5.2.1 on 2026-02-06 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_cascade_event_deletes'),
        ('landing', '0008_alter_newscomment_options_alter_newspost_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name_plural': 'Matches'},
        ),
        migrations.AlterField(
            model_name='trainingseminarparticipation',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Event this athlete participated in', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seminar_participations', to='landing.event'),
        ),
    ]
