# Generated by Django 6.1 on 2026-09-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_remove_competition_referee_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='display_mode',
            field=models.CharField(choices=[('reveal_final', 'Afișare finală'), ('real_time', 'Arbitraj în timp real')], default='real_time', max_length=20, verbose_name='Mod afișare'),
        ),
    ]
