# Generated by Django 5.2.1 on 2026-02-07 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_fix_athletematch_event_column_sqlite'),
        ('landing', '0008_alter_newscomment_options_alter_newspost_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryrefereescore',
            name='deductions',
            field=models.JSONField(blank=True, default=dict, help_text='Deductions by category: wrong_technique, wrong_position, not_looking_real, stamina'),
        ),
        migrations.AlterField(
            model_name='categoryrefereescore',
            name='score',
            field=models.DecimalField(decimal_places=2, default=100, help_text='Final score: 100 minus all deductions', max_digits=5),
        ),
        migrations.CreateModel(
            name='CompetitionField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Field name (e.g., "Field 1", "Tatami A", "Area B")', max_length=100)),
                ('field_number', models.IntegerField(help_text='Numeric identifier for the field')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this field is currently being used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(help_text='The event this field belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='landing.event')),
            ],
            options={
                'verbose_name': 'Competition Field',
                'verbose_name_plural': 'Competition Fields',
                'ordering': ['field_number'],
                'unique_together': {('event', 'field_number')},
            },
        ),
        migrations.CreateModel(
            name='DisplayMonitorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('displaying', 'Displaying'), ('scores_revealed', 'Scores Revealed')], default='idle', help_text='Current display status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_athlete', models.ForeignKey(blank=True, help_text='The current athlete being displayed (for solo/teams)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitor_sessions', to='api.athlete')),
                ('current_category', models.ForeignKey(blank=True, help_text='The category currently displayed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitor_sessions_category', to='api.category')),
                ('current_match', models.ForeignKey(blank=True, help_text='The match currently displayed (for fighting categories)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitor_sessions_match', to='api.match')),
                ('field', models.OneToOneField(help_text='Which field this monitor serves', on_delete=django.db.models.deletion.CASCADE, related_name='monitor_session', to='api.competitionfield')),
            ],
            options={
                'verbose_name': 'Display Monitor Session',
                'verbose_name_plural': 'Display Monitor Sessions',
            },
        ),
        migrations.CreateModel(
            name='CategoryFieldAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', help_text='Current status of this category on this field', max_length=20)),
                ('scheduled_start_time', models.DateTimeField(blank=True, help_text='When the category is scheduled to start', null=True)),
                ('actual_start_time', models.DateTimeField(blank=True, help_text='When the category actually started', null=True)),
                ('actual_end_time', models.DateTimeField(blank=True, help_text='When the category actually ended', null=True)),
                ('order', models.IntegerField(default=0, help_text='Order in which categories are run on this field')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.OneToOneField(help_text='The category being assigned', on_delete=django.db.models.deletion.CASCADE, related_name='field_assignment', to='api.category')),
                ('field', models.ForeignKey(help_text='The field this category is assigned to', on_delete=django.db.models.deletion.CASCADE, related_name='category_assignments', to='api.competitionfield')),
            ],
            options={
                'verbose_name': 'Category Field Assignment',
                'verbose_name_plural': 'Category Field Assignments',
                'ordering': ['order'],
                'indexes': [models.Index(fields=['field', 'status'], name='api_categor_field_i_4b9e7b_idx')],
            },
        ),
        migrations.CreateModel(
            name='MatchRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(help_text='Round number (1, 2, 3, etc.)')),
                ('duration_seconds', models.IntegerField(default=180, help_text='Duration of this round in seconds (default 3 minutes)')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('completed', 'Completed')], default='scheduled', help_text='Current status of this round', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, help_text='When the round started', null=True)),
                ('ended_at', models.DateTimeField(blank=True, help_text='When the round ended', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(help_text='The match this round belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='api.match')),
            ],
            options={
                'verbose_name': 'Match Round',
                'verbose_name_plural': 'Match Rounds',
                'ordering': ['round_number'],
                'unique_together': {('match', 'round_number')},
            },
        ),
        migrations.CreateModel(
            name='QRCodeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Unique QR code value', max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this QR code can be used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date for this QR code', null=True)),
                ('category', models.ForeignKey(blank=True, help_text='The category this QR code grants access to (solo/teams only)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_assignments', to='api.category')),
                ('match', models.ForeignKey(blank=True, help_text='The match this QR code grants access to (fighting only)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_assignments', to='api.match')),
                ('referee', models.ForeignKey(help_text='The referee this QR code is for', limit_choices_to={'is_referee': True}, on_delete=django.db.models.deletion.CASCADE, related_name='qr_assignments', to='api.athlete')),
            ],
            options={
                'verbose_name': 'QR Code Assignment',
                'verbose_name_plural': 'QR Code Assignments',
                'indexes': [models.Index(fields=['code'], name='api_qrcodea_code_211aa9_idx'), models.Index(fields=['referee', 'category'], name='api_qrcodea_referee_bb0f8d_idx'), models.Index(fields=['referee', 'match'], name='api_qrcodea_referee_f3c5c7_idx')],
                'unique_together': {('referee', 'category', 'match')},
            },
        ),
    ]
