# Generated by Django 6.1 on 2026-09-21 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_match_display_mode_default_real_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='refereepresence',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='refereepresence',
            name='match',
            field=models.ForeignKey(blank=True, help_text='Meciul pe care îl arbitrează acest arbitru (probe de luptă).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referee_presences', to='api.match', verbose_name='Meci'),
        ),
        migrations.AlterField(
            model_name='refereepresence',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Categoria pe care o arbitrează acest arbitru (probe solo/echipă).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referee_presences', to='api.category', verbose_name='Categorie'),
        ),
        migrations.AddConstraint(
            model_name='refereepresence',
            constraint=models.UniqueConstraint(condition=models.Q(('category__isnull', False)), fields=('category', 'referee'), name='unique_category_referee_presence'),
        ),
        migrations.AddConstraint(
            model_name='refereepresence',
            constraint=models.UniqueConstraint(condition=models.Q(('match__isnull', False)), fields=('match', 'referee'), name='unique_match_referee_presence'),
        ),
    ]
