# Generated by Django 6.1 on 2026-09-21 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_referee_presence_match'),
        ('landing', '0021_event_organizing_club'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefereeQRLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creat la')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizat la')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referee_qr_logins', to='landing.event', verbose_name='Eveniment')),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_logins', to='api.athlete', verbose_name='Arbitru')),
            ],
            options={
                'verbose_name': 'Login QR arbitru',
                'verbose_name_plural': 'Login-uri QR arbitri',
                'unique_together': {('event', 'referee')},
            },
        ),
    ]
