# Generated by Django 6.1 on 2026-09-23 16:59

import secrets

from django.db import migrations, models


PIN_LENGTH = 5


def backfill_pins(apps, schema_editor):
    """Referees issued a QR login before this migration have no PIN, and
    the model only mints one on save - so without this they'd be the one
    group that can't use the device, and only on the events that matter
    (the ones already set up)."""
    RefereeQRLogin = apps.get_model('api', 'RefereeQRLogin')
    span = 10 ** PIN_LENGTH
    used = set(
        RefereeQRLogin.objects.exclude(pin=None).values_list('pin', flat=True)
    )
    for row in RefereeQRLogin.objects.filter(pin=None):
        for _attempt in range(50):
            candidate = f'{secrets.randbelow(span):0{PIN_LENGTH}d}'
            if candidate not in used:
                used.add(candidate)
                row.pin = candidate
                row.save(update_fields=['pin'])
                break


def drop_pins(apps, schema_editor):
    # Reversing only removes the column, so there is nothing to undo.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_userproxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefereePinLoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True, verbose_name='Adresă IP')),
                ('pin_tried', models.CharField(blank=True, max_length=8, verbose_name='PIN încercat')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creat la')),
            ],
            options={
                'verbose_name': 'Încercare login PIN arbitru',
                'verbose_name_plural': 'Încercări login PIN arbitru',
            },
        ),
        migrations.AddField(
            model_name='refereeqrlogin',
            name='pin',
            field=models.CharField(blank=True, db_index=True, max_length=8, null=True, unique=True, verbose_name='PIN'),
        ),
        migrations.RunPython(backfill_pins, drop_pins),
    ]
