# Generated by Django 6.1 on 2026-09-30 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_refereepinloginattempt_refereeqrlogin_pin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competitionfield',
            options={'ordering': ['field_number'], 'verbose_name': 'Teren de concurs', 'verbose_name_plural': 'Terenuri de concurs'},
        ),
        migrations.AlterModelOptions(
            name='fightcategory',
            options={'verbose_name': 'Categorie de luptă', 'verbose_name_plural': 'Categorii de luptă'},
        ),
        migrations.AlterModelOptions(
            name='gradehistory',
            options={'verbose_name': 'Istoric de grad', 'verbose_name_plural': 'Istorice de grad'},
        ),
        migrations.AlterModelOptions(
            name='matchrefereescore',
            options={'verbose_name': 'Scor de arbitru pentru meci', 'verbose_name_plural': 'Scoruri de arbitru pentru meciuri'},
        ),
        migrations.AlterModelOptions(
            name='trainingseminarparticipation',
            options={'verbose_name': 'Participare la seminar', 'verbose_name_plural': 'Participări la seminare'},
        ),
        migrations.AlterField(
            model_name='athlete',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Revizuit de'),
        ),
        migrations.AlterField(
            model_name='athletematch',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Revizuit de'),
        ),
        migrations.AlterField(
            model_name='categoryathletescore',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Revizuit de'),
        ),
        migrations.AlterField(
            model_name='gradehistory',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Revizuit de'),
        ),
        migrations.AlterField(
            model_name='trainingseminarparticipation',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Revizuit de'),
        ),
        migrations.AlterField(
            model_name='visa',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Note ale administratorului despre aprobare sau respingere.', null=True, verbose_name='Note administrator'),
        ),
        migrations.AlterField(
            model_name='visa',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Revizuit de'),
        ),
        migrations.AlterField(
            model_name='visa',
            name='status',
            field=models.CharField(choices=[('pending', 'În așteptarea aprobării'), ('approved', 'Aprobat'), ('rejected', 'Respins'), ('revision_required', 'Necesită revizie')], default='approved', help_text='Starea aprobării (implicit aprobat pentru înregistrările adăugate de administrator).', max_length=20, verbose_name='Stare'),
        ),
    ]
