# Generated by Django 6.1.1 on 2026-10-03 09:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_alter_competitionfield_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='pending_profile_image_focus_x',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Focus imagine în așteptare - orizontal (%)'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='pending_profile_image_focus_y',
            field=models.PositiveSmallIntegerField(default=25, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Focus imagine în așteptare - vertical (%)'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='profile_image_focus_x',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Focus imagine - orizontal (%)'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='profile_image_focus_y',
            field=models.PositiveSmallIntegerField(default=25, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Focus imagine - vertical (%)'),
        ),
    ]
