# Generated by Django 6.1.1 on 2026-10-04 00:14

"""Scoate `Athlete.team_place`.

Era un camp ramas din schema initiala: text liber, unul singur pe sportiv,
nelegat de vreo competitie - deci al doilea rezultat de echipa l-ar fi
suprascris pe primul, iar ce ramanea spunea "locul 2" fara sa spuna unde si
cand. Rezultatele de echipa se tin de mult in CategoryAthleteScore
(type='teams', team_members, placement_claimed, cu flux de aprobare), de
unde se calculeaza si medaliile - vezi medal_counts_for_athlete, care nu
s-a uitat niciodata la campul asta.

Stergerea unei coloane pierde date, asa ca s-a numarat intai: zero valori in
productie, zero in baza de dezvoltare, zero in cei 75 de sportivi adusi prin
pachetul de eveniment. Nu se pierde nimic.
"""

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_athlete_profile_image_focus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='team_place',
        ),
    ]
