# Generated by Django 6.1.1 on 2026-10-05 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_drop_athlete_team_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryFlowEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('start', 'Proba a inceput'), ('present', 'Sportivul prezinta'), ('stop', 'Sportivul a terminat'), ('finish', 'Proba s-a incheiat')], max_length=20, verbose_name='Acțiune')),
                ('team_name', models.CharField(blank=True, max_length=255, verbose_name='Echipă')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Moment')),
                ('video_offset_ms', models.IntegerField(blank=True, null=True, verbose_name='Decalaj video (ms)')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadate')),
                ('athlete', models.ForeignKey(blank=True, help_text='Doar la prezentare și la oprire.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_flow_events', to='api.athlete', verbose_name='Sportiv')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_events', to='api.category', verbose_name='Categorie')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_flow_events', to=settings.AUTH_USER_MODEL, verbose_name='Creat de')),
                ('recording_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_flow_events', to='api.fieldrecordingsession', verbose_name='Sesiune înregistrare')),
            ],
            options={
                'verbose_name': 'Eveniment din desfășurarea probei',
                'verbose_name_plural': 'Evenimente din desfășurarea probelor',
                'ordering': ['timestamp', 'id'],
                'indexes': [models.Index(fields=['category', 'timestamp'], name='api_categor_categor_018749_idx')],
            },
        ),
    ]
