# Generated by Django 5.2.1 on 2026-02-08 22:20

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfoProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('landing.contactinfo',),
        ),
        migrations.CreateModel(
            name='ContactMessageProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('landing.contactmessage',),
        ),
    ]
