# Generated by Django 5.2.1 on 2026-02-08 22:20

import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=100)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('image_alt', models.CharField(blank=True, help_text='Alt text for image (SEO)', max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Order in which sections appear')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Sections',
                'ordering': ['order', 'section_title'],
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('social_media_facebook', models.URLField(blank=True)),
                ('social_media_instagram', models.URLField(blank=True)),
                ('social_media_twitter', models.URLField(blank=True)),
                ('business_hours', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Business Hours')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
                ('is_replied', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for staff')),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='SEO title (60 chars max). If empty, uses the main title.', max_length=60)),
                ('meta_description', models.CharField(blank=True, help_text='SEO description (160 chars max)', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='SEO keywords, separated by commas', max_length=255)),
                ('canonical_url', models.URLField(blank=True, help_text='Canonical URL to avoid duplicate content')),
                ('robots_index', models.BooleanField(default=True, help_text='Allow search engines to index this page')),
                ('robots_follow', models.BooleanField(default=True, help_text='Allow search engines to follow links on this page')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly version of the title', unique=True)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('address', models.TextField(blank=True, help_text='Full address of the event')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('featured_image_alt', models.CharField(blank=True, help_text='Alt text for featured image (SEO)', max_length=100)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('event_type', models.CharField(choices=[('competition', 'Competition'), ('examination', 'Examination'), ('training_seminar', 'Training Seminar')], default='competition', help_text='Type of event', max_length=32)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('past', 'Past')], default='upcoming', help_text='Operational status of the event', max_length=16)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tags', models.CharField(blank=True, help_text='Tags separated by commas', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('city', models.ForeignKey(blank=True, help_text='Select a city for this event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='api.city')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='SEO title (60 chars max). If empty, uses the main title.', max_length=60)),
                ('meta_description', models.CharField(blank=True, help_text='SEO description (160 chars max)', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='SEO keywords, separated by commas', max_length=255)),
                ('canonical_url', models.URLField(blank=True, help_text='Canonical URL to avoid duplicate content')),
                ('robots_index', models.BooleanField(default=True, help_text='Allow search engines to index this page')),
                ('robots_follow', models.BooleanField(default=True, help_text='Allow search engines to follow links on this page')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly version of the title', unique=True)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content')),
                ('excerpt', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Excerpt')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('featured_image_alt', models.CharField(blank=True, help_text='Alt text for featured image (SEO)', max_length=100)),
                ('published', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('tags', models.CharField(blank=True, help_text='Tags separated by commas', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(help_text='Only admin users can be authors', limit_choices_to={'role': 'admin'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Comment content (1000 chars max)', max_length=1000)),
                ('is_approved', models.BooleanField(default=True, help_text='Whether the comment is approved for display')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent comment for threaded replies', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='landing.newscomment')),
                ('news_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='landing.newspost')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsPostGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news/gallery/')),
                ('alt_text', models.CharField(blank=True, help_text='Alt text for the image (SEO)', max_length=100)),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the image', max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Order in which images appear in gallery')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('news_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='landing.newspost')),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
