# Generated by Django 5.2.1 on 2025-10-30 13:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='author',
            field=models.ForeignKey(help_text='Only admin users can be authors', limit_choices_to={'role': 'admin'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='NewsPostGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news/gallery/')),
                ('alt_text', models.CharField(blank=True, help_text='Alt text for the image (SEO)', max_length=100)),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the image', max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Order in which images appear in gallery')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('news_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='landing.newspost')),
            ],
            options={
                'verbose_name': 'News Gallery Image',
                'verbose_name_plural': 'News Gallery Images',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
