# Generated by Django 5.2.1 on 2025-10-30 22:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_alter_newspost_author_newspostgallery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Comment content (1000 chars max)', max_length=1000)),
                ('is_approved', models.BooleanField(default=True, help_text='Whether the comment is approved for display')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('news_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='landing.newspost')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent comment for threaded replies', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='landing.newscomment')),
            ],
            options={
                'verbose_name': 'News Comment',
                'verbose_name_plural': 'News Comments',
                'ordering': ['created_at'],
            },
        ),
    ]
