# Generated by Django 5.2.1 on 2025-11-05 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_add_newscomment_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='max_participants',
        ),
        migrations.RemoveField(
            model_name='event',
            name='registration_link',
        ),
        migrations.RemoveField(
            model_name='event',
            name='registration_required',
        ),
    ]
