# Generated by Django 5.2.1 on 2025-11-05 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_gradehistory_exam_date_gradehistory_event'),
        ('landing', '0004_remove_event_max_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.ForeignKey(blank=True, help_text='Select a city for this event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='api.city'),
        ),
    ]
