# Generated by Django 5.2.1 on 2025-11-05 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_event_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
    ]
