# Generated by Django 5.2.1 on 2025-11-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_remove_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('competition', 'Competition'), ('examination', 'Examination'), ('training_seminar', 'Training Seminar')], default='competition', help_text='Type of event', max_length=32),
        ),
    ]
