# Generated by Django 5.2.1 on 2025-11-06 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_event_event_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newscomment',
            options={'ordering': ['created_at'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='newspost',
            options={'ordering': ['-created_at'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='newspostgallery',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Gallery Image', 'verbose_name_plural': 'Gallery Images'},
        ),
    ]
