# Generated by Django 6.1 on 2026-09-06 16:18

import django.utils.timezone
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0012_event_sync_history_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly version of the title', unique=True)),
                ('url', models.URLField(help_text='Full YouTube or Vimeo video URL (e.g. https://www.youtube.com/watch?v=... or https://vimeo.com/...)')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='videos/')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Description')),
                ('published', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['-created_at'],
            },
        ),
    ]
