# Generated by Django 6.1 on 2026-09-06 17:38

import django.utils.timezone
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0013_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly version of the title', unique=True)),
                ('category', models.CharField(choices=[('regulament', 'Regulament'), ('documente', 'Documente')], default='documente', max_length=20)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Description')),
                ('file', models.FileField(blank=True, help_text='PDF or other downloadable document', null=True, upload_to='documents/')),
                ('external_url', models.URLField(blank=True, help_text="Use instead of/alongside 'file' if the document is hosted elsewhere")),
                ('published', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0, help_text='Order in which documents appear within their category')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['category', 'order', '-created_at'],
            },
        ),
    ]
