# Generated by Django 6.1 on 2026-09-07 15:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_club_public_fields'),
        ('landing', '0014_documentpage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='newspostgallery',
            name='tagged_athletes',
            field=models.ManyToManyField(blank=True, help_text="Athletes tagged in this photo - shown on their public profile 'Poze' tab", related_name='tagged_photos', to='api.athlete'),
        ),
        migrations.AddField(
            model_name='newspostgallery',
            name='tagged_clubs',
            field=models.ManyToManyField(blank=True, help_text="Clubs tagged in this photo - shown on the club's public 'Poze' tab", related_name='tagged_photos', to='api.club'),
        ),
        migrations.CreateModel(
            name='GalleryComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Comment content (1000 chars max)', max_length=1000)),
                ('is_approved', models.BooleanField(default=True, help_text='Whether the comment is approved for display')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('gallery_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='landing.newspostgallery')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent comment for threaded replies', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='landing.gallerycomment')),
            ],
            options={
                'verbose_name': 'Photo Comment',
                'verbose_name_plural': 'Photo Comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('gallery_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='landing.newspostgallery')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Photo Reaction',
                'verbose_name_plural': 'Photo Reactions',
                'unique_together': {('gallery_image', 'user')},
            },
        ),
    ]
