# Generated by Django 6.1 on 2026-09-09 11:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0015_newspostgallery_tagged_athletes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('news_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='landing.newspost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Article Reaction',
                'verbose_name_plural': 'Article Reactions',
                'unique_together': {('news_post', 'user')},
            },
        ),
    ]
