# Generated by Django 6.1.1 on 2026-09-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0016_newsreaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentpage',
            name='slug',
            field=models.SlugField(help_text='URL-friendly version of the title', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(help_text='URL-friendly version of the title', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='slug',
            field=models.SlugField(help_text='URL-friendly version of the title', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(help_text='URL-friendly version of the title', max_length=255, unique=True),
        ),
    ]
