# Generated by Django 6.1.1 on 2026-09-12 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_athlete_is_licensed_athlete_license_request_document'),
        ('landing', '0017_alter_documentpage_slug_alter_event_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='tagged_athletes',
            field=models.ManyToManyField(blank=True, help_text='Athletes tagged in this video - shown on their public profile and the Media page', related_name='tagged_videos', to='api.athlete'),
        ),
        migrations.AddField(
            model_name='video',
            name='tagged_clubs',
            field=models.ManyToManyField(blank=True, help_text="Clubs tagged in this video - shown on the club's public page and the Media page", related_name='tagged_videos', to='api.club'),
        ),
    ]
