# Generated by Django 6.1 on 2026-09-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_athlete_referee_category'),
        ('landing', '0019_event_event_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='tagged_athletes',
            field=models.ManyToManyField(blank=True, help_text="Athletes mentioned in this post - surfaced in their coach's feed", related_name='tagged_news', to='api.athlete'),
        ),
    ]
