# Generated by Django 6.1 on 2026-09-16 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_club_youtube_url'),
        ('landing', '0020_newspost_tagged_athletes'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizing_club',
            field=models.ForeignKey(blank=True, help_text='Set only for a club-organized exam - excluded from the public calendar.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_events', to='api.club'),
        ),
    ]
