# Generated by Django 6.1.1 on 2026-09-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0021_event_organizing_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_publicly_visible',
            field=models.BooleanField(default=True, help_text='Show this event on the public site. Uncheck to keep it admin-only.'),
        ),
    ]
