# Generated by Django 6.1 on 2026-09-30 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0022_event_is_publicly_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='status',
        ),
    ]
