# Generated by Django 5.2.1 on 2026-02-08 22:20

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('landing.newscomment',),
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('landing.newspostgallery',),
        ),
        migrations.CreateModel(
            name='NewsCommentProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('landing.newscomment',),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('landing.newspost',),
        ),
    ]
