# Generated by Django 5.2.1 on 2025-11-06 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        # This migration was generated earlier but we keep it as a no-op to
        # avoid removing models that were subsequently renamed. The actual
        # rename is done in 0002_rename_proxy_models.py; leaving this
        # migration empty preserves history without destructive deletes.
    ]
