# Generated by Django 5.2.1 on 2025-11-09 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_alter_newscomment_options_alter_newspost_options_and_more'),
        ('news', '0003_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCommentProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('landing.newscomment',),
        ),
    ]
